export const artistData = [
    {
        "id": "SorryYouth",
        "artist": "拍謝少年",
        "band_img": "https://akstatic.streetvoice.com/profile_images/So/rr/SorryYouth/f622bc988a3d11e196660026551ae608.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_images/So/rr/SorryYouth/f622bc988a3d11e196660026551ae608.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 17,
        "follower": 6696,
        "following": 1,
        "content": ""
    },
    {
        "id": "ChihSiou_",
        "artist": "持修",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Ch/ih/ChihSiou_/jrd5FcGHpVyRSSpUYPRgrc.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Ch/ih/ChihSiou_/NiiCu6N9WmKthJxLqr62yA.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 6,
        "follower": 22732,
        "following": 3,
        "content": "性別：男\n生日 / 成立時間：11 月 20 日\n\n持修Instagram：chih_siou"
    },
    {
        "id": "nightkeepers2015",
        "artist": "Night Keepers 守夜人",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ni/gh/nightkeepers2015/qv8zE5udaTMNbEU87u46vG.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/ni/gh/nightkeepers2015/vghs634ZxDj6rKHRTYFkNN.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 19,
        "follower": 12032,
        "following": 10,
        "content": "\n【活在自己的世界】https://youtu.be/vTvPtgUs_Bc【關於守夜人樂團】\nNight Keepers守夜人樂團，於 2015年正式成軍，最初遊走在電影配樂與遊戲作曲中，之後在各類音樂創作與現場演出中成形，目前成員為團長旭章、主唱稚翎與鼓手其偉，電吉他手佳穎，合作bass手林羿妏，並持續以跨界合作方式推出作品。\nNight Keepers是少數擁有不同身份使命的創作組合，時而涉足電玩，時而出版圖文詩集，有時只是用音樂表達一個失眠人對這世界的種種期待、躲藏、痛苦與觀察。\n守夜人的音樂以充滿敘事性、神經質的鋼琴與節奏作基底，輔以迷幻的電吉他音牆，搭上雙主唱的隨性哼唱，共同譜寫出溫暖而童心未泯的安眠旋律。\n守夜人期望能扮演『睡不著使者』，用音樂、文字、影像、設計、live 演出與聽眾互相交流，並透過人工智慧軟體『聊天機器人』,與聽眾在睡前互相記錄、交換自己空虛、痛苦、孤獨的故事，藉此達到一種『團體治療』的效果，讓每個人都有機會成為彼此的守護者(Keepers)。\n▲更多活動資訊請關注⭐️Facebook__Night Keepers 守夜人⭐️Instagram__nightkeepers2019⭐️Youtube＿Night Keepers https://youtu.be/vTvPtgUs_Bc"
    },
    {
        "id": "OldSlutDistortion",
        "artist": "老破麻 - Old Slut Distortion",
        "band_img": "https://akstatic.streetvoice.com/profile_images/co/ok/cooknight/5nWFghLYke8V7EMDZ2QUAP.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/co/ok/cooknight/jTNZTYF5KTa5LJBHL9cRxm.jpg",
        "type_": "音樂人",
        "place": "臺中市",
        "songs": 14,
        "follower": 5164,
        "following": 17,
        "content": "\n畢竟生活就像被強暴，要是躲不開你只能學會享受。所以享受著生活強暴的你我他，我們都是人生中的老破麻。 \n\"你可以嘲笑我們的團名，但是不要忘記那也是為了逗你開心。\" \nSometimes life will FUCK YOU UP so hard that you gotta turn around, get fucked in another position, and enjoy it like how an OLD SLUT WOULD. So go hard or go home, live the old slut LIFE.\n\"Laugh at us if you will, but remember that we brought a smile to your DAMN FACE.\"\n粉絲專頁：https://www.facebook.com/Oldslot.b1/\n獲獎經歷:2016台東鐵花村焚風音樂大賞決賽鐵團獎（第一名）2017大安沙雕音樂季熱音大賽第一名2018 12th舊愛新歡-古典詩詞譜曲創作暨演唱競賽 狀元（第一名）"
    },
    {
        "id": "iruka527",
        "artist": "イルカポリス 海豚刑警",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ir/uk/iruka527/o44qTZrMZWPuNjYogygF4i.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/ir/uk/iruka527/vPTfUoREiZLS5UsswiApmc.png",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 8,
        "follower": 10726,
        "following": 22,
        "content": "生日 / 成立時間：2017 年 5 月 27 日\n\n♡♡♡? 海豚刑警 ♡♡♡?大家注意==！！哈皮^^~❣２０１７屁團誕生(⁎⁍̴̛ᴗ⁍̴̛⁎)❣❣~☆,,*••﹏海豚刑事總部正式發佈出道處女秀新聞稿@@==！！！主幹道由一把電吉他與一把木吉他先行拿下==！！支流配置==！一些豚豚平常就會拿來噗累噗累ㄉ玩具聲響，，最後再加上淑芬志明雙主唱旋轉跳躍華麗組成@@..朗朗上口ㄉ旋律==！了無新意ㄉ和弦==！曲風多變==！歌詞偏不流俗==！狗年初加入ㄌ彈指之間御用旋律線夢想導師aka金發把拔抖指引~與擔任待引爆抖哈姆太郎「咚咚」角色aka進擊抖鼓手正雄，在這ㄍ壞噗噗(Bad poo poo)抖世界，揪讓婐悶一起~~!!~!!!~陰蒂Rock一夏芭٩(˃̶͈̀௰˂̶͈́)و❣⚡️⚡️❣❣！！！\nhttps://www.facebook.com/iruka0.0\n@iruka0.0"
    },
    {
        "id": "wearewang",
        "artist": "老王樂隊",
        "band_img": "https://akstatic.streetvoice.com/profile_images/we/ar/wearewang/Xac9wSmB5pcSJmi2YCjS6X.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/we/ar/wearewang/Cx5aMAtQGsEjwEZyb9Ked5.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 12,
        "follower": 34459,
        "following": 22,
        "content": "生日 / 成立時間：2015 年 10 月 27 日\n\n民謠搖滾臉書：https://www.facebook.com/yourwomansleepwithothers/微博：https://m.weibo.cn/u/6364009385?uid=6364009385&luicode=10000011&lfid=1076036396826066歡迎私訊捐款"
    },
    {
        "id": "sweetjohnband",
        "artist": "甜約翰 Sweet John",
        "band_img": "https://akstatic.streetvoice.com/profile_images/sw/ee/sweetjohnband/mveDwE8xmrN5owyTvuM6Ye.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/sw/ee/sweetjohnband/k2CQDQF3H6Y9b5tjQ2qyqD.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 17,
        "follower": 27177,
        "following": 11,
        "content": "性別：男\n\n在我們最美麗的年華，讓我們相遇，就讓遺憾與美好藏在旋律裡。\n『謝謝妳/你，在我們最美麗的年華，讓我們相遇， 就讓遺憾與美好藏在旋律裡。』\n甜約翰前身為成立於 2011 年，來自台南的 Natural Outcome 自然發聲樂團，主唱浚瑋、吉他手罐頭、貝斯手阿獎以及鼓手小 J 相遇於成大，成團後經歷進入社會的焦慮以及討生活的矛盾，沈潛兩年後在 2016 的一個雨天裡遇見Mandark，從此開啟甜約翰的嶄新篇章。 \n團名的 Sweet John 源自於專與情人、伴侶道別的「Dear John Letter」，甜約翰擅長以輕快小品式的旋律，內斂且溫柔的呢喃出首首獨白。揉和多種器樂聲響以及風格元素，延續 Natural Outcome 的五人編制以及對於律動的完美掌握，編織出屬於甜約翰式的小品慵懶，獻給每位聽者心中，如此美好卻只能揮手告別的 Sweet John。\n主唱：浚瑋　鍵盤：Mandark　吉他：罐頭　貝斯：阿獎　鼓：小J\nFacebook： https://www.facebook.com/sweetjohnband/Youtube： https://www.youtube.com/channel/UCGdLLM0CekFmgMhPpnG9A7Q"
    },
    {
        "id": "gaopuihuechia",
        "artist": "狗吠火車",
        "band_img": "https://akstatic.streetvoice.com/profile_images/04/06/0406D5/TVLonHkcHdRXPhWSxnqAgn.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_images/04/06/0406D5/TVLonHkcHdRXPhWSxnqAgn.jpg",
        "type_": "音樂人",
        "place": "臺中市",
        "songs": 2,
        "follower": 26,
        "following": 1,
        "content": "\n在台灣傳統俚語中狗吠火車是表示徒勞無功的意思。如果生命中接踵而來的未知挑戰就像一列疾駛而來的火車，儘管我們似乎無法閃避這些巨大的衝擊，卻依舊本能的用力吶喊對抗我們無法掌握的一切，故我吠故我在。"
    },
    {
        "id": "ConstantanChange",
        "artist": "康士坦的變化球",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Co/ns/ConstantanChange/5Kng83jHUXCJb2vMRPG9mh.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Co/ns/ConstantanChange/cqei9yACaXAZRaPV5pNMCQ.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 3,
        "follower": 13946,
        "following": 1,
        "content": "性別：其他\n\n關於康士坦的變化球 KST Post Rock為「恆定」基底，試著加入各種「改變」元素，多一點強烈節奏，多一點吉他聲線，多一點複雜的鼓點編寫，將各種嘗試放到音樂裡試驗催化，組合出超越後搖的基本想像，就像是灰色的天空飄散著淡淡的彩色香氣，看似平衡卻似墜落，既迷幻又真實，內斂卻開放。唯一不變的就是變；世間萬物每一刻都在變動，沒有一樣是靜止的；我們不可能保持固定，只能維持動態的平衡。平衡所散發出的能量，將推往無限。成員吉他手：CREED吉他手：ARNY貝斯手： SION鼓手：小米VJ：啟泰"
    },
    {
        "id": "bobistired",
        "artist": "逃走鮑伯",
        "band_img": "https://akstatic.streetvoice.com/profile_images/bo/bi/bobistired/JVFFC9AKKz6ZVmS53KhQ69.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_images/bo/bi/bobistired/JVFFC9AKKz6ZVmS53KhQ69.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 7,
        "follower": 2216,
        "following": 34,
        "content": ""
    },
    {
        "id": "EastWaveBand",
        "artist": "EastWave",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Ea/st/EastWaveBand/xGyo2r9KnMrVNLXzjgmwYQ.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Ea/st/EastWaveBand/pQPBZtikyE4vHBLgaqTLwd.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 11,
        "follower": 872,
        "following": 0,
        "content": "\n成立於2017年，由主唱 郭子恆（Jemmy）, 吉他 夏敬淳（Frankie）, 貝斯 鄧凱文（Kevin）, 鼓手 曾景崧（Relaxx）所組成，2019年 Keyboard 卞宗仁（小卞） 加入。 我們享受在不同角度下看待一件事情摩擦出的火花，時而激烈又溫柔，抓住自己還能任性一回的時間做覺得酷的事！  \n創作始終來自生活，紀錄這個時代背景下所產生的感受，將世界上所發生美好不美好的事藉『幻想』為題抒發情感，在現實的妥協與困難中仍能保有一絲勇氣面對下一個挑戰。"
    },
    {
        "id": "bike9662",
        "artist": "BIKE機踏車樂團",
        "band_img": "https://akstatic.streetvoice.com/profile_images/bi/ke/bike9662/DuwmArmB4NeaQCy8fRZdbe.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/bi/ke/bike9662/7yFY3aCq46ysW5MBvUrtg4.jpg",
        "type_": "音樂人",
        "place": "臺中市",
        "songs": 32,
        "follower": 448,
        "following": 12,
        "content": "\n來自台中的搖滾樂團，由主唱育嘉於2005年成立，並於2013年發行首張專輯 [嘿！我想一下]，曲風以復古老搖滾和disco 還有流行龐克混種而成，演出現場張力十足並感染力強.\nBIKE機踏車樂團FBhttps://www.facebook.com/biketaiwanbandBIKE機踏車樂團IGhttps://www.instagram.com/bikerockband/BIKE機踏車樂團IndieVoxhttps://www.indievox.com/bike9662BIKE機踏車樂團YouTubehttps://www.youtube.com/user/bike9662/videos\n陳如山 阿山(四分衛樂團主唱)\n無論何時何地，只要戴上耳機，踩上BIKE的踏板， 不管是輕輕地踩，還是狠狠地用盡全力， 面對迎面而來的風，吹散了許多不經意的青澀風景， 這趟擁有青春印記的旅行，都一定會前進。\n蔡政忠 馬瓜(資深樂評人)\n成軍於台中，創作經營許久的BIKE樂隊，是個帶有著正面能量與信念的power trio。主唱張育嘉歌聲高亢明亮，退伍後重新再起，透過音樂描寫摩登城市中關於人群與生活的種種，讓人不禁回想起八零年代東方快車合唱團。這首「城市漫步」，除了得以一窺他們對生活的真切感受外，源源不絕的搖滾熱情，更是其魅力所在！"
    },
    {
        "id": "piscoband",
        "artist": "P!SCO",
        "band_img": "https://akstatic.streetvoice.com/profile_images/pi/sc/pisco/2552e43c456f11e38574123150003041.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/pi/sc/pisco/9yY6SXwGz8YUTWg46o2RHX.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 39,
        "follower": 3648,
        "following": 22,
        "content": "\n“我們就是要毫不猶豫的帶來快樂”\n樂迷封為最能挑戰肌耐力極限的跳舞搖滾樂團。極具情緒煽動力以及強大的現場演出實力迅速成為各大音樂祭的主力，演出視野延伸至日本，港澳及中國；曾受日本富士電視台，愛知電視台專訪，首次日本公演獲得極佳的票房。\n毫不間斷的演出風格，讓P!SCO超有特色。電子迷離曲風混搭歡愉舞曲節奏，大量使用合成器和古典鋼琴創造了絕對獨特的P!SCO曲風；演出時和台下樂迷的互動創造了強大的演出氣場，樂迷自主成立後援會，有趣的舞台動作讓台上台下玩成一片。P!SCO固定發表特殊企劃的樂團週邊商品總是造成搶購，銷售一空。\n接下來P!SCO樂團將繼續走向世界舞台，我們絕對帶著滿滿的誠意和源源不絕的活讓大家感到絕對的快樂。來吧！加入我們。暖身完畢後就跟我們作陣跳舞啦～～\nP!SCO websitehttp://www.piscoband.com\nP!SCO 周邊商品線上商店http://www.shapa-art.com/shop.php?html=product&type=10000/10058/10062http://store.piscoband.com/\nYoutube Channelhttp://www.youtube.com/user/piscochannel\nTwitterhttps://twitter.com/PiscoBand\n新浪微博http://weibo.com/piscoband\nInstagramhttp://instagram.com/piscoband\nUstreamhttp://www.ustream.tv/channel/p-scoustream"
    },
    {
        "id": "dizLike",
        "artist": "dizLike",
        "band_img": "https://akstatic.streetvoice.com/profile_images/di/zL/dizLike/M6DijbvRfhdPTd4dtoPLrB.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/di/zL/dizLike/K63quLGFrmE8XhVeAhtext.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 6,
        "follower": 886,
        "following": 1,
        "content": "性別：其他\n\n| dizLike 大團誕生年終人氣票選開跑中 | 如果你喜歡我們請投我們一票投票網址： https://streetvoice.com/pages/thenextbigthing-2020-vote/\ndizLike音譯dislike，有點任性、有點叛逆的我們，更忠於自己的聲音 『 我就是我，管你喜不喜歡，只有我們可以不喜歡。 』 \n於2018組成的搖滾女子樂團要用可愛的外表加上最有態度的音樂來征服你！來自北中南的妹力，甜到你不愛都不行\n♥ 追蹤dizLike Facebook：https://www.facebook.com/dizliketw/Instagram：https://www.instagram.com/dizliketw"
    },
    {
        "id": "Cmypenis",
        "artist": "Carnival",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Cm/yp/Cmypenis/kLfkf2eEVd2UoUKYtM52gY.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Cm/yp/Cmypenis/ao7MUP7U2wEBPRyRiiN9Cw.jpg",
        "type_": "音樂人",
        "place": "臺中市",
        "songs": 1,
        "follower": 22,
        "following": 2,
        "content": ""
    },
    {
        "id": "nononsensecollective",
        "artist": "無妄合作社No-nonsense Collective",
        "band_img": "https://akstatic.streetvoice.com/profile_images/no/no/nononsensecollective/whFDNZjVfAEH6uQB7J2MGa.jpeg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/no/no/nononsensecollective/CshWi2bcYybKarCmhNWc2D.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 7,
        "follower": 5550,
        "following": 27,
        "content": "\n由四個不事生產的懶人組成的樂團，成立以來在台北、基隆與台東等地進行創作，音樂受啟發自香菸焦油、林間野味與都市廢氣。\n易經：「無妄之疾，勿藥有喜」，突然得了死不了的病，不吃藥就會痊癒。對於種種欲加諸承擔的文明，我們不願戒斷與根治。\n====\n郭力瑋: guitar & vocal謝秉男: guitar & vocal謝碩元: bass邱孝齊: drum\n歷任團員:\n林昀鋒林肯\nFACEBOOK : https://www.facebook.com/nononsense.collective/微博：https://weibo.com/u/6396826066"
    },
    {
        "id": "ironhorn",
        "artist": "宋德鶴Iron Horn",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ir/on/ironhorn/DFKb6dMvim7EqjX39SLPzQ.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/ir/on/ironhorn/V2QFBeb6gu3kc8KywdPskH.jpg",
        "type_": "音樂人",
        "place": "彰化縣",
        "songs": 10,
        "follower": 1907,
        "following": 10,
        "content": "性別：男\n\n我們是來自彰化的宋德鶴 2016年發行第一張單曲 《迷路》2017年拿下金門國際海島音樂祭冠軍2015年由郭振華(Bass)發起彰化大型音樂祭《回歸》由宋德鶴擔任主辦樂團至今已經第4屆，一直留在彰化為自己的家鄉推廣著。我們歌曲描繪了我們眼前所見到的事實，也將身邊聽到的故事記錄下來，一直沒有中斷想要做出感動人的歌曲，而所謂快樂總是讓人容易忘記，而痛苦卻是深刻無比，將這一切成為你我的故事，讓強顏歡笑的你感覺到悲傷，也讓悲傷的你找到那一點點的光芒，跟我們一起大哭大笑。"
    },
    {
        "id": "SADOG",
        "artist": "SADOG",
        "band_img": "https://akstatic.streetvoice.com/profile_images/we/ak/weakfreak/CzJNLzmixLxnHLiGkhvxT3.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/SA/DO/SADOG/9rRWxcXuDkxu2LKxxZwQKT.png",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 49,
        "follower": 1443,
        "following": 48,
        "content": "\nWe're the SADOG, Not a kind of dog.來自桃園臺地，四個叛客少年。唱著混了藍調跟一些髒東西的藍調龐克。歌詞跟樂句都充滿鐵漢柔情的男子漢硬派作風。由整團最老，18歲的情傷男子漢--佐藤、一樣18歲的冷酷吉他手--亞破、17歲的糙老臉bass手--建勳、天真有邪的16歲鼓手--子瑜，所組成。\n非常非常歡迎邀請我們表演。我們真的很愛表演，超級希望你們能邀請我們表演。請來信：tsaihe2927@gmail.com我會含著淚說謝謝。"
    },
    {
        "id": "mainlive",
        "artist": "米老虎 MainLive",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ma/in/mainlive/cmzAWGroeW7AJqndgsF3Mp.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/ma/in/mainlive/nHKaYGGL7kfMDPq2hWU4Kc.jpg",
        "type_": "音樂人",
        "place": "新北市",
        "songs": 5,
        "follower": 300,
        "following": 1,
        "content": ""
    },
    {
        "id": "LumiXu",
        "artist": "許含光 Lumi",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Lu/mi/LumiXu/ED7q4qcULwLpjT88vQ4bu.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_images/Lu/mi/LumiXu/ED7q4qcULwLpjT88vQ4bu.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 1,
        "follower": 4685,
        "following": 0,
        "content": "性別：男\n\n許含光Lumi\n1993 年生於臺北市，臺北市立成功高中畢業，現就讀國立臺灣大學。學生，歌手，文字創作者。\n2012 年起曾參與多部微電影與廣告配樂、 2013 年 9 月舉辦首次不插電演唱會、2014年七月三號在小河岸初登臺。2015年九月在Legacy mini舉辦live & unplugged演出。2017年全台《借一杯咖啡的時間》咖啡廳 mini tour 演出20場。\n音樂風格受英式搖滾和電子樂影響深遠，以吉他創作的民謠色彩為基調，捕捉對生命裡大小事的慾望和想像的模樣，慢慢地吟唱。\n2016年起陸續發表個人音樂作品。2017年12月5日個人首張全自作專輯《曖曖 A Portrait of My Mile Way》正式發行。\nFB - www.facebook.com/iamLumiXu/ IG - www.instagram.com/lumi.xu/"
    },
    {
        "id": "lukechan168",
        "artist": "荷爾蒙少年 Hormone Boys",
        "band_img": "https://akstatic.streetvoice.com/profile_images/lu/ke/lukechan168/cnRmHwi4kbbkZvMJaaXFSV.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/lu/ke/lukechan168/JVzkuK9So5fNJssW8nP78n.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 12,
        "follower": 11074,
        "following": 16,
        "content": "\n荷爾蒙少年是一種狀態，自溺而溫柔、叛逆卻善良。\n為了拼湊出屬於九零末的新聲音，在龐克、日搖和disco funk元素之間不停轉換嘗試，氾濫的少年抑鬱、卻少不了俏皮叛逆的模樣。也許外在就如同團名般稚氣瀟灑，可現場演出的張力，帶來的絕對是不亞於專輯裡的震撼。\n（文/詹詠安、陳玄佾）\n-\nWe are HormoneBoys from Taiwan.\nIn order to assemble the new voice to represent the late 90s, we kept trying to switch different elements from punk to Japanese style rock n roll and even to disco funk. \nDepressions of the teenagers were drowning but they never lack the face of a witty rebel. Appearing innocent as their title of the band, elegant but unconventional, the shock and power they have for the audience in live shows will definitely astound you far more than the album itself does.\n（Writing / Yuki Lin）\n歡迎追蹤我們的臉書及instagram：https://www.facebook.com/Hormoneboys/https://www.instagram.com/hormoneboys_/"
    },
    {
        "id": "aun04178ofe",
        "artist": "温蒂漫步 Wendy wander",
        "band_img": "https://akstatic.streetvoice.com/profile_images/au/n0/aun04178ofe/i3yCC4aEPULnywTQF4DYPQ.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/au/n0/aun04178ofe/8ntCuHHvMSNT4UEPoN8Qfm.png",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 13,
        "follower": 4064,
        "following": 14,
        "content": "\n你心中的浪漫是什麼樣子？ 收到日思夜盼的那封信， 重新上檔的舊電影， 還是相擁漫舞在大雨裡。 我們都在用不同的方式， 為自己所憧憬的愛祈禱。 將一切染成粉色， 讓春天融化在夢裡。\nFacebookhttps://www.facebook.com/pages/category/Band/%E6%BA%AB%E8%92%82%E6%BC%AB%E6%AD%A5-Wendy-Wander-2004247253029598/Instagramhttps://www.instagram.com/wendywanderofficial/?igshid=63z4mw4rqxhkApple Musichttps://music.apple.com/tw/album/spring-spring/1538088304spotifyhttps://open.spotify.com/artist/5YVLwkimiEhl8L409NfySF?si=3XN3TTd7TJmjZUeC2hK8QQKKBOXhttps://kkbox.fm/ep1X42微博 https://www.weibo.com/wendywander?is_all=1網易雲音樂 https://music.163.com/#/album?id=97417165"
    },
    {
        "id": "831",
        "artist": "八三夭",
        "band_img": "https://akstatic.streetvoice.com/profile_images/83/1/831/71fdab12739811e39124123142ff1218.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_images/83/1/831/71fdab12739811e39124123142ff1218.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 6,
        "follower": 476,
        "following": 2,
        "content": "性別：男\n\nhttps://www.facebook.com/band831tw"
    },
    {
        "id": "MixerMiSir",
        "artist": "麋先生Mixer",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Mi/xe/MixerMiSir/mPjUyKbpRDx4eoVqVHupUb.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Mi/xe/MixerMiSir/yef2HJbF8yAup74HKDmGdj.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 10,
        "follower": 8253,
        "following": 1,
        "content": "性別：男\n\n麋先生Mixer //\n❝ 我們不知道最高的地方在哪但我們上路了你們的同行會讓我們更勇敢的踏下每一步❞ \n五位團員均來自台灣南部，陸續從學生時期就因音樂而相識，進而北上在2012年10月正式組團成為【麋先生Mixer】‧2013年發行首張創作專輯《馬戲團運動》，並以此專輯拿下2014年第25屆金曲獎最佳樂團獎‧2014年經過近5個月的比賽流程，拿下公視【音樂創世紀】創作冠軍‧2014年9月榮獲外交部邀約，代表台灣新生代樂團前往東北亞地區，在日本東京、福岡與韓國釜山三個城市進行音樂文化交流巡演。‧2015年3月發行第二張創作專輯《沒名字的人類》，並以此專輯入圍2016年第27屆金曲獎最佳樂團獎。‧2016年3月發行第三張創作專輯《野生》。‧2018年12月於臺大體育館舉辦首場大型售票演唱會。\n麋先生以淋漓暢快的曲風和耐人尋味的文字風格，廣受各界喜愛，從北到南受邀參與校園演出、各大音樂節與商業場的邀約不斷，以一場場現場演唱展開音樂旅途的麋先生，所到之處不分台上、台下，全場就是一個舞台，包括你我！\n────────麋先生│Mixer 團員────────聖皓 Vocal喆安 A.Guitar小B E.Guitar以諾 Bass逸凡 Drums────────麋先生官方‧Mixer Official────────◢ Facebook https://fb.com/MixerMiSir◢ YouTube https://www.youtube.com/MixerMisir◢ Instagram https://instagram.com/mixerband_official"
    },
    {
        "id": "arrowwei",
        "artist": "魏嘉瑩 Arrow Wei",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ar/ro/arrowei/EnKqacA59mBHd9wMy58bh8.JPG?x-oss-process=image/resize,m_fill,h_600,w_600,limit_0/interlace,1/quality,q_95/sharpen,80/format,jpg), .jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_images/ar/ro/arrowei/EnKqacA59mBHd9wMy58bh8.JPG?x-oss-process=image/resize,m_fill,h_360,w_1920,limit_0/interlace,1/quality,q_95/sharpen,80/format,jpg), .jpg",
        "type_": "音樂人",
        "place": "臺中市",
        "songs": 6,
        "follower": 2292,
        "following": 3,
        "content": "性別：女\n生日 / 成立時間：5 月 14 日\n\n將活到目前為止所感受的人生經驗、喜怒哀樂，匯聚成歌。\n不停的淬煉，不斷在舞台上演唱著。\n黑暗中帶點微光的療癒，\n將世界巨大的悲傷，暗藏在旋律中，\n帶著陽光與黑暗的矛盾，衝擊著各個角落。"
    },
    {
        "id": "yasakamark",
        "artist": "吳青原",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ya/sa/yasakamark/WWvGj4AKzAZhzvYXk5zYM5.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/ya/sa/yasakamark/Fo5Q67u6aQmX9e9JYWH5Xe.jpg",
        "type_": "音樂人",
        "place": "嘉義縣",
        "songs": 12,
        "follower": 4838,
        "following": 14,
        "content": "\n吳青原 | 寫歌的人 旅行的人用歌紀錄旅程中人與人的相遇。就算是迷惘徬徨的心情、離別時的痛苦，都應該被溫柔安放。\n希望有一天我們都能輕捧愛的重量，好好聆聽自己內在深處的聲音，讓踏出的每一步，踩出扎實的腳印。\n。2018年發行了第一張創作專輯《親愛的準備好要出發了嗎》。總結了幾年在台灣旅行生活的總總。\n/粉絲專業連結https://www.facebook.com/aquiver.tt/\n/ig帳號 : yasakamark⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀線上支持青原的歌?Amazon : https://goo.gl/YWENAxKKBOX： https://goo.gl/kwU3uhSpotify： https://goo.gl/WJuxBD\n購買實體專輯https://reurl.cc/G7Wg3"
    },
    {
        "id": "bbulter",
        "artist": "王彙筑",
        "band_img": "https://akstatic.streetvoice.com/profile_images/bb/ul/bbulter/ikDMajb95EfoD5DTDa5Qsg.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/bb/ul/bbulter/7KJp3hQpWkfU9vWAd3JHP7.jpg",
        "type_": "音樂人",
        "place": "台灣",
        "songs": 7,
        "follower": 1087,
        "following": 51,
        "content": ""
    },
    {
        "id": "Eustache",
        "artist": "生炒鴨肉羹",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Eu/st/Eustache/hfGB738m482xtvN4BrvpgY.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Eu/st/Eustache/JCsdTTNW2SioicPfbFgUno.jpg",
        "type_": "音樂人",
        "place": "嘉義縣",
        "songs": 12,
        "follower": 412,
        "following": 5,
        "content": "生日 / 成立時間：2016 年 2 月 29 日\n\n粉專連結：https://m.facebook.com/h.j.band.0229/嗨 我們是生炒如果 聆聽著生炒的音樂的你正和我們一樣為了成為心中的樣子而努力著那希望藉由這些故事能夠觸碰到心裡最真實的你"
    },
    {
        "id": "bisiugroup",
        "artist": "美秀集團",
        "band_img": "https://akstatic.streetvoice.com/profile_images/bi/si/bisiugroup/9AyvUU9FcJib4aDzA7efRS.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/bi/si/bisiugroup/qQWjkhixxuJnMDuczQGRrL.jpg",
        "type_": "音樂人",
        "place": "新北市",
        "songs": 6,
        "follower": 24754,
        "following": 0,
        "content": "性別：其他\n生日 / 成立時間：2016 年 5 月 27 日\n\n美秀集團,來自嘉義的低科技俗氣樂隊,以實驗樂器結合搖滾聲響,加上民謠、龐克等元素,帶領觀眾進入愛與欺騙的情慾世界。\n【重要資歷】獲得2018海洋音樂祭「評審團大賞」首張EP「Sound Check」入圍第八屆金音獎最佳新人「Sound Check」巡迴台中場,入圍第八屆金音獎最佳現場演出獲得「2017硬地專輯錄製補助案:專輯類」補助，共80萬獲得「2018硬地音樂行銷推廣」補助，共70萬《懶趴火》入圍第八屆金音獎最佳搖滾單曲《捲菸》youtube點擊150萬《Only Scott Knows》被選為ANGUS CHIANG倫敦時裝周配樂《一隻雞》獲臺灣原創流行音樂大賞(河洛語組貳獎)《電火王》獲臺灣原創流行音樂大賞(河洛語組參獎)《細粒的目睭》收錄於南面而歌合輯\n【演出經歷】2016 覺醒音樂祭2016 混種現場2016 巨獸搖滾音樂祭2016 愛愛搖滾帳篷音樂節2017 嘉義跨年晚會2017 首張EP「Sound Check」噴出巡迴2017 大港開唱2017 覺醒音樂祭2017 金音獎演出2018 嘉義跨年晚會2018 覺醒音樂祭2018 《電火王》專輯實驗巡迴2018 無限自由藝術祭2018 愛愛搖滾帳篷音樂節\n【集團成員】狗柏 Gobo|主唱、低科技發明家、電火王|Vocal, Installation Artist, King of Light修齊 Hsiu Chi|吉他手|Guitarist珮慈 Amie|貝斯手|Bassist冠佑 Luis|鍵盤手|Keyboardist鍾錡 Kenny|鼓手|Drummer\n聯絡人:劉修齊手機:0961199542信箱:m920333333@gmail.com"
    },
    {
        "id": "thetictac",
        "artist": "The Tic Tac",
        "band_img": "https://akstatic.streetvoice.com/profile_images/th/et/thetictac/xvKfQ9awQTQWqWHFfoC38J.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/th/et/thetictac/8WRb2EuJtyzsLYY9CiNYUo.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 25,
        "follower": 781,
        "following": 14,
        "content": "\n2019 年推出最新 EP《Golden Age 你所以為的美好》\nThe Tic Tac 於 2008年組成，2010年發首張EP《U Have to Go》，2013年於鐵皮屋錄製EP《Taken》，2015年正式發行首張專輯《正常的生活》，並於2017年推出黑膠《當他們來臨之前 / 這個城市需要睡眠》。\n樂風遊走在民謠和獨立搖滾之間，現場表演以劇場敘事感為主要訴求，每一首歌曲都是他們對於社會觀察而產生的魔幻小故事，故事不真實卻又寫實地描繪現代社會人與人的關係。\n音樂上，The Tic Tac追求一種自由的關係，不拘泥於曲風或是樂器，偏向打擊樂的演奏方式，帶給Tic Tac一種自然壯闊的氛圍，尋找極致微小的寧靜，追求狂躁巨大的噪音，敘事畫面感強烈，將帶給聽眾相當不同的感受。"
    },
    {
        "id": "skippylu",
        "artist": "Crispy脆樂團",
        "band_img": "https://akstatic.streetvoice.com/profile_images/sk/ip/skippylu/sCkruNHPEsBtyyvdutPQQ9.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/sk/ip/skippylu/YZbRHKoMiq3g5TjBS3oJBL.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 17,
        "follower": 9841,
        "following": 41,
        "content": "性別：其他\n\n【表演 各項活動邀約】請洽經紀人 玫芸 Email：m688586@gmail.com電話：0978688586【facebook】http://www.facebook.com/CrispyCrispyCrispy【Instagram】@crispytheband【微博】http://www.weibo.com/crispycrispycrispy\nCrispy脆樂團，由男主唱兼吉他手 Skippy 以及女主唱兼多功能樂手丁丁所組成，為雙主唱雙人組合，成軍於2010年。\nCrispy脆樂團以Skippy為創作首腦，從日常生活出發，敘事般的口吻圍繞成長的各個面向。以木吉他為基底，Skippy清澈細膩的嗓音帶著幾分稚氣男孩的氣息，與丁丁多層次的歌聲交織，形成Crispy獨特的聲響，再搭配取樣器的 loop、電子合成器、鍵盤音色與音效，營造出豐富多樣的音樂氛圍，時而清新明亮、時而迷幻惆悵、時而搖滾吶喊，反應成長所經歷的不同心境層面。"
    },
    {
        "id": "AOIMUSHIBAND",
        "artist": "青虫 aoi",
        "band_img": "https://akstatic.streetvoice.com/profile_images/AO/IM/AOIMUSHIBAND/fs4FctcNfjbBF4tTMfh66R.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/AO/IM/AOIMUSHIBAND/33Vcjx3K4byxi6XCeC62Vd.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 36,
        "follower": 3312,
        "following": 43,
        "content": "生日 / 成立時間：2017 年 6 月 3 日\n\n青是青鳥的青、虫是王虫的虫。成軍於 2017 年夏季，創作涵蓋華語、台語、英語，曲風民謠骨電子皮，直白的歌詞搭著朗朗上口的旋律，音樂如蟲子一般，鑽進聽眾的耳朵裡就此定居。活動、合作邀約：aoimushiband@gmail.com\n青虫aoi Band Members吉尼／Vocal&Guitar郭宏／Bass信展／Drums黄柏翰／Electric Guitar \n2020年青虫aoi首張專輯《有你的故事ū lí ê kòo-sū》\n◉ 搶先聽預告◉6月22日（一）20:00將在 StreetVoice 釋出三首完整曲目聽一聽有沒有你的故事\n►2020.06.30 數位平台發行➩https://aoi.lnk.to/firstalbum2020.08.14 實體全面上架\n↳ Follow us on Instagram：aoimushiband"
    },
    {
        "id": "whocares2016",
        "artist": "Who Cares 胡凱兒",
        "band_img": "https://akstatic.streetvoice.com/profile_images/wh/oc/whocares2016/UtXtGY8tpKofXxr2UB8EhC.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/wh/oc/whocares2016/BoNyPEbPbuUZHF4Z5HG24h.png",
        "type_": "音樂人",
        "place": "臺中市",
        "songs": 11,
        "follower": 7782,
        "following": 5,
        "content": "\n“Who Cares? ”2016年4月成立於台中第三人稱單數後面動詞要加s，很重要。\n我們是胡凱兒。"
    },
    {
        "id": "thickbigband",
        "artist": "粗大Band",
        "band_img": "https://akstatic.streetvoice.com/profile_images/th/ic/thickbigband/BsMsfu7CLRGSxQ8EJBg2NU.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/th/ic/thickbigband/gimLyfcyeQK4h4HwmPnzKc.png",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 20,
        "follower": 1097,
        "following": 13,
        "content": "\n粗大Band： Facebookhttps://www.facebook.com/thickbigband粗大Band： Instagramhttps://www.instagram.com/thickbigband"
    },
    {
        "id": "leowangmorrison",
        "artist": "Leo王",
        "band_img": "https://akstatic.streetvoice.com/profile_images/le/ow/leowangmorrison/599da82c16ea11e68a6d0ae52af18be5.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/le/ow/leowangmorrison/84a1f97875144cc2af4125108e0969b1.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 30,
        "follower": 10880,
        "following": 0,
        "content": "性別：男\n生日 / 成立時間：1993 年 10 月 29 日\n\nLeo王，沙發王，有舊的沙發何必買新的沙發，嘴裡碎念著你爸媽不想讓你聽到的歪理，但其實那些都是他對這世界的期許。\n來自顏社，念念唱唱，搖搖擺擺。\nLeo Wang, rapper and singer based in Taipei, Taiwan, began playing in rock bands at the age of 17. Later, he started rapping when he started smoking. Musically influenced by Radiohead, The Doors, Bone Thugs-n-Harmony, Jurassic 5, Maceo Parker, and Jay Chou,Leo Wang is about trying to combine jazz, hip-hop, reggae, and scat singing with Mandarin Chinese in a groovy way,and making his people dance.官方網站： https://www.facebook.com/LeoWangSofaKing"
    },
    {
        "id": "faasofficial",
        "artist": "FUTURE AFTER A SECOND",
        "band_img": "https://akstatic.streetvoice.com/profile_images/fa/as/faasofficial/ihzoLMYRBwjeZgcC4F7FZS.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/fa/as/faasofficial/UbvbugUSmg9fWaqa4dgeZf.png",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 6,
        "follower": 350,
        "following": 0,
        "content": "性別：其他\n\nFUTURE AFTER A SECOND，來自台北的Metalcore樂團，自2014年成立以來不斷嘗試將post-hardcore的旋律融合metalcore、numetal的節奏發展出獨樹一幟的風格，也一直努力在創造與樂迷在演出現場的各種連結可能性。於2017年發行首張EP<To the Light>，演出用大量肢體語言及情緒煽動觀眾，搭配強烈的視覺呈現獲得好評，於2017年5月進行東京地區巡迴，並加入日本廠牌Far channel Record，2017年底發起以Livehouse金屬場景為主的第一屆Autumn Attack，希望以團結的理念，讓金屬樂可以獲得更多的焦點。\nFAAS在2019年8月發行首張專輯<OFiN>，以”現在即是未來的“理念貫穿專輯，希望在這個時代，我們得謹慎選擇每一步，別讓我們所擁有的自由，在自己的手上消失。\n2020年FAAS<OFiN>專輯以<Invert>奪得全美獨立音樂獎最佳金屬單曲，並以最佳專輯封面設計與<Invert>最佳短片導演獲得入圍肯定。"
    },
    {
        "id": "punktv",
        "artist": "非人物種",
        "band_img": "https://akstatic.streetvoice.com/profile_images/pu/nk/punktv/W48SxoAy7pmhabSA8V7y5W.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/pu/nk/punktv/TJjPoHU9h2haWxrM7Kxc95.jpg",
        "type_": "音樂人",
        "place": "基隆市",
        "songs": 16,
        "follower": 1442,
        "following": 37,
        "content": "性別：男\n\n成員:：    撥屎 / Bass, Vocal    阿顯 / Guitar, Vocal    智明 / Guitar, Vocal    阿來/ Drums\n現實拖磨少年時的夢，生活跟理想你要選那一項？這是成為男子漢的必經路程。\n踏著黑紫色的雲彩，口中哼著不成調的音階來到人世間，三頭六臂手持雞腿降臨凡間，帶給俗世人們無盡的苦惱與納悶，毫無頭緒的前奏，騎虎難下的主歌，風流倜儻的副歌與不知所措的結語，狂亂的嘶吼猶如天蓬元帥下凡，雜亂無章的演奏彷彿春天的水溝，帶給你莫名奇妙又充滿快感帶點尷尬的氛圍。\n才氣充滿的粗獷4人樂隊專門救災，切西瓜。\n非人物種（Inhuman）\nContact : inhumanbandok@gmail.com活動洽詢:70.6jt7@gmail.com"
    },
    {
        "id": "heatsketch",
        "artist": "熱寫生 heat sketch",
        "band_img": "https://akstatic.streetvoice.com/profile_images/he/at/heatsketch/yDFqZtLfVJrKASzE3Rd3k4.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/he/at/heatsketch/CbCUUiEsAd2KVCvvYFizdi.png",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 16,
        "follower": 2473,
        "following": 0,
        "content": "\n2020/2/16 《豆皮少年》發片專場購票：https://reurl.cc/alWAR4"
    },
    {
        "id": "RIGband",
        "artist": "倒車入庫 Reversing into Garage",
        "band_img": "https://akstatic.streetvoice.com/profile_images/RI/Gb/RIGband/AzwG9JDPaxEdFVjnZWEC63.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/RI/Gb/RIGband/2N9T5aX4jtefxNMbMpcQMa.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 8,
        "follower": 2412,
        "following": 12,
        "content": "\n倒車入庫 Reversing into Garage 來自台北六張犁的車庫龐克樂隊。\n來自台北六張犁，車庫龐克樂隊。\n站在社會陰暗角落，莫名的歇斯底里，\n以狹隘卻自以為獨道的視野觀察眼前事物，\n「交流道旁的檳榔攤」、「朋友的朋友自殺前的日記」、「今天月亮好大」、「啊... 這個路燈壞了」、「燙傷藥膏的廣告」\n生活不起眼的狗屁小事，在心中激起莫名波瀾。\n不在乎社會如何變化，不在乎黑夜過去迎來的白晝或末日。\n聯繫：黑市音樂 bmmptw@gmail.com"
    },
    {
        "id": "wayofpuzzle",
        "artist": "謎路人Way of Puzzle",
        "band_img": "https://akstatic.streetvoice.com/profile_images/wa/yo/wayofpuzzle/wmeHWGKYjUXEpTHypPf5JX.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/wa/yo/wayofpuzzle/3chf2H7bYsoEAAp2hPNVm.jpg",
        "type_": "音樂人",
        "place": "高雄市",
        "songs": 11,
        "follower": 4088,
        "following": 22,
        "content": "性別：男\n\n未來人生，對我們來說總是像個謎。一塊永遠都缺少一片的拼圖。在抉擇的路上時常迷失方向，然而相信音樂能夠為人們找到出口的四個人以此為概念在2014年組成了Way of Puzzle謎路人。希望創作出能幫助和自己一樣對於未來迷惘的年輕人找到方向，對於音樂能夠撫慰人心深信不疑也期待能夠在音樂的路上找到更多相同理念的夥伴。\n  曲風以new metal夾雜metal core及post-hardcore為底延伸出多變的曲風，元素融合雷鬼及饒舌風格。呼應了人生中有許多未知數的道路，令人惶恐不安。詞曲呈現多以訴說對於新世代面臨的壓力及競爭下的內心情境。四個來自高雄的年輕人要用他們的音樂與更多族群形成共鳴。"
    },
    {
        "id": "angry_youth",
        "artist": "厭世少年",
        "band_img": "https://akstatic.streetvoice.com/profile_images/an/gr/angry_youth/Vh8LQbyGos5f9ju5DdwmFc.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/an/gr/angry_youth/RVtvdSopuzBQx9yRu8Godg.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 21,
        "follower": 4036,
        "following": 0,
        "content": "性別：男\n\n在這個惡意滿盈的時代，我們選擇苦中作樂"
    },
    {
        "id": "thefurofficial",
        "artist": "The Fur.",
        "band_img": "https://akstatic.streetvoice.com/profile_images/th/ef/thefurofficial/7ZboF5wSJc9wmNhe4P2nvu.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/th/ef/thefurofficial/NHDuGWC26LuFtMx3CM4Nzk.png",
        "type_": "音樂人",
        "place": "高雄市",
        "songs": 8,
        "follower": 3187,
        "following": 0,
        "content": "\nThe Fur. 是一支夢幻、獨立流行樂團，由廖柚文擔任詞曲創作者，吳中凌編曲，於2016年底創立。朗朗上口的旋律與清澈歌聲，帶來夢幻的合成流行樂和獨立搖滾的曲風。The Fur.於2018年發行了首張專輯《Town》，即以《Town》入圍第30屆金曲獎GMA最佳新人獎；第10屆GIMA金音獎最佳新人獎；歌曲〈Short Stay〉則是入圍最佳另類流行單曲，依專輯首張拿下相當好的成績！除臺灣活動以外，The Fur.於2019年美國奧斯汀南方音樂節SXSW首次亮相，更在成立初期出演2018年西班牙春之聲音樂節 (Primavera Sound)、英國Focus Wales，以及泰國曼谷Cat Expo5參與演出。積極投入國內外活動的The Fur.，目前正在籌備第二張全新創作專輯，預計於2020年發行。"
    },
    {
        "id": "nckn",
        "artist": "南西肯恩",
        "band_img": "https://akstatic.streetvoice.com/profile_images/nc/kn/nckn/oNfUMGhgaGpvrNn4AtLECW.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/nc/kn/nckn/HXqcsD9xT5JgjGfzMAPL9B.jpg",
        "type_": "音樂人",
        "place": "新北市",
        "songs": 10,
        "follower": 18546,
        "following": 0,
        "content": "\n南西肯恩首張正式 EP《那麼我想再擁有自己》【數位平台點聽】http://bit.ly/那麼我想再擁有自己\n【FACEBOOK】https://www.facebook.com/ncknband/【INSTAGRAM】ID: ncknband【CONTACT】黑市音樂bmmptw@gmail.com"
    },
    {
        "id": "sleepingbrain",
        "artist": "眠腦 Sleeping Brain",
        "band_img": "https://akstatic.streetvoice.com/profile_images/sl/ee/sleepingbrain/cC72MtcM7BuX4nRXnJuq8c.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/sl/ee/sleepingbrain/U6HG8Zr83aS3vHDfCo2S2C.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 8,
        "follower": 768,
        "following": 32,
        "content": "性別：男\n\nFacebook：http://www.facebook.com/sleepingbrainInstagram：https://www.instagram.com/sleepingbrain/\n現場演出及活動相關：黑市音樂 bmmptw@gmail.con"
    },
    {
        "id": "huanhuantw",
        "artist": "緩緩 Huan Huan",
        "band_img": "https://akstatic.streetvoice.com/profile_images/hu/an/huanhuantw/XRed6pfJSjrMtYdudots4L.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/hu/an/huanhuantw/3uuyxSSmBtqPsogC2ShJaA.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 18,
        "follower": 1936,
        "following": 21,
        "content": "\n2020 New Single Released in 8th, April《I'd better be on time》https://youtu.be/QSeG4ocIxH0\nFollow us:‣ Instagram｜https://www.instagram.com/huanhuantw/‣ Facebook  |  https://www.facebook.com/HuanHuanTW/‣ Bandcamp|  https://huanhuan.bandcamp.com/‣ Twitter       |  https://twitter.com/huanhuantw\n「眷戀海洋的溫度／卻無法適應潮汐的洶湧／他離開之後／在失速的列車上／緩慢生活。」\n緩緩，來自台北的另類搖滾樂團。受到後搖滾啟發，於民謠基底中加入瞪鞋／硬地搖滾／電子等元素，時而溫暖時而暴烈，帶你走進海洋深處，體會真正的柔軟，當海湧來時，所有記憶將被帶向遠方。\nHuan Huan is an alternative indie band from Taipei. Their music incorporates elements of post-rock/ shoegaze/ dreampop and electronic. Trying to interpret things in a soft but resilient way.Singing for lost things; Making sounds for healing.\n#indiepop#post-rock#dreampop#slowcore#alternative"
    },
    {
        "id": "wanlongband",
        "artist": "萬龍 WANLONG",
        "band_img": "https://akstatic.streetvoice.com/profile_images/wa/nl/wanlongband/2wJ7VTpDL7AdBU2deWxTYx.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/wa/nl/wanlongband/mqmKtPrMAaY7aXhu3BpXhJ.png",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 7,
        "follower": 437,
        "following": 0,
        "content": "\n福爾摩沙橫空出世熱氣蒸騰、有龍飛出！\n活動邀演｜wanlong.band@gmail.com"
    },
    {
        "id": "mycateatsmyhand",
        "artist": "My Cat Eats My Hand",
        "band_img": "https://akstatic.streetvoice.com/profile_images/my/ca/mycateatsmyhand/3RzPHtqvYskNKT3AHd8s5Q.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/my/ca/mycateatsmyhand/kuhjUYbMMZQGiNazsrqpVY.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 6,
        "follower": 214,
        "following": 44,
        "content": "性別：其他\n生日 / 成立時間：2017 年 4 月 1 日\n\nMy Cat Eats My Hand are\n徐徹天 / Vocal & Guitar鄒達平 / Guitar符真瑋 / Bass江力軍 / Drum郭佳陵 / Keyboard\nfacebook： https://www.facebook.com/mycateatsmyhand/Instagram：https://www.instagram.com/my_cat_eats_my_handYoutube : https://www.youtube.com/mycateatsmyhand\n沒有走在時代尖端，也不跟隨所謂的潮流，只是專心致志走在我們所認定的「搖滾樂的樣貌」之道路上。\n2017年4月，在抱著「回歸搖滾樂原點」的心情下組成了這個樂團。在樂團成立初期，創團成員皆深受1990以及2000年代美國及日本搖滾樂團的影響，也因此定調了alternative rock, punk rock, post-grunge, j-rock的基本音樂表現風格。\n編曲構成方面，在渾厚扎實的硬式吉他搖滾的基調中融入鋼琴編曲，展現更多編曲上的可能性，也使充滿力道的音樂中有些細膩柔和的聲線。"
    },
    {
        "id": "tizzybac",
        "artist": "Tizzy Bac",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ti/zz/tizzybac/HIMGP_652933.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_images/ti/zz/tizzybac/HIMGP_652933.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 3,
        "follower": 1665,
        "following": 1,
        "content": ""
    },
    {
        "id": "waynessosad",
        "artist": "Wayne's so sad 傷心欲絕",
        "band_img": "https://akstatic.streetvoice.com/profile_images/wa/yn/waynessosad/v2Cm2TcEzyaCgVy9n8BEb6.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/wa/yn/waynessosad/5eh2gnpiLGqBD45bShrjF8.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 7,
        "follower": 7357,
        "following": 0,
        "content": "\n傷心欲絕，來自台北的搖滾樂團。IG：https://www.instagram.com/waynes_so_sad/FB：https://www.facebook.com/waynesosad/\n樂團成員：許正泰｜劉暐｜葛亭筠｜陳冠甫｜黃紹祖｜官靖剛"
    },
    {
        "id": "greeneyesmusic",
        "artist": "Green!Eyes",
        "band_img": "https://akstatic.streetvoice.com/profile_images/gr/ee/greeneyesmusic/86d32a7c380811e59edb0026551b1100.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/gr/ee/greeneyesmusic/1fb0a24db75743d7919f91dfee9e5d34.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 6,
        "follower": 899,
        "following": 2,
        "content": "性別：男\n\nGreen!Eyes love you."
    },
    {
        "id": "punkhoo",
        "artist": "胖虎 punkhoo",
        "band_img": "https://akstatic.streetvoice.com/profile_images/pu/nk/punkhoo/6PFq5dcQpLEKxSGhb6XDub.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/pu/nk/punkhoo/Hsdm6m2d9aZr8SqoKefZCG.jpg",
        "type_": "音樂人",
        "place": "新北市",
        "songs": 19,
        "follower": 1194,
        "following": 8,
        "content": "性別：男\n\n成立於2003年，進入樂團運作的第17年，由初期的美式pop punk逐漸轉變為節奏感強烈、編曲結構緊密的Melodic punk，為台灣首屈一指三人龐克團第一指名，曾擔任日本龐克名團locofrank台灣巡迴之共演團。2014年中展開迷你專輯「反轉未來」之亞洲巡迴，長達一個月多達20座城市的大型巡迴。2016年發行第四張最新單曲「facelife」。現場演出張力、群眾號召力以及現場煽動力皆為台灣龐克圈數一數二之樂團。與前公司結束合作後，樂團自組廠牌「這邊音樂那邊設計｜HereThere Studio」自主經營。\nwebsite | www.punkhoo.comfacebook | www.facebook.com/punkhooinstagram | www.instagram.com/punkhoo_official/youtube | www.youtube.com/user/punkhoo"
    },
    {
        "id": "APHASIAtw",
        "artist": "阿飛西雅 APHASIA",
        "band_img": "https://akstatic.streetvoice.com/profile_images/AP/HA/APHASIAtw/6FKmmJWF4hFFXrWqgxu95U.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/AP/HA/APHASIAtw/b628xRwTuysz4jkwCtRVhD.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 10,
        "follower": 615,
        "following": 1,
        "content": "\n阿飛西雅是台灣的另類搖滾樂團！關注所有社會議題與文化現象，讓其音樂有著與其他樂團全然不同的表述，阿飛西雅的世界不從自我開始，也不在自我結束，而訴求一種「不光只是音樂」的普遍經驗。他們投入社會，透過自省，以樂曲言明觀點，邏輯清楚地昭示未來向行的方向。努力地追求真實，用從容的態度去面對混亂。阿飛西雅的音樂本身便是，看似直接卻複雜的意識。他們是不編造任何謊言，希望正面給予聽眾觸發與衝擊。"
    },
    {
        "id": "fleshjuicer",
        "artist": "Flesh Juicer 血肉果汁機",
        "band_img": "https://akstatic.streetvoice.com/profile_images/fl/es/fleshjuicer/gVCDkDaBdGCqEqsbnH6BCR.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/fl/es/fleshjuicer/QCFqhQT8HLrEwkbi2fi94b.jpg",
        "type_": "音樂人",
        "place": "臺中市",
        "songs": 28,
        "follower": 3641,
        "following": 2,
        "content": "性別：男\n\n血肉果汁機在2016年5月結束成立十年首次專場大型演出「血肉宮：建宮蓋廟演唱會」，開演前門票即全數銷售一空，如此盛況在台灣INDIE金屬樂團不算常見，而且在此之前鮮少有人會將台灣廟會與金屬文化融合在一起。血肉果汁機不僅將兩者強烈展現在音樂風格之中，現場表演的視覺呈現也是相當具有特色，更別忘了主唱Gigo頭上那頂在大拜拜時才會看到的死豬頭。\n血肉果汁機成立於2006年，風格以DEATHCORE和HARDCORE為主，現任成員為主唱Gigo、吉他手ZERO、吉他手Matt、貝斯手sionC和鼓手Evan。2009年發行首張 EP「下體潰爛 A Morbid State」，2011年發行第二張EP「粗殘台中 The Brutal Taichung」，整張風格以臺灣傳統旋律為基底出發，有別於以往的金屬風格。2015年發行第一張完整專輯「GIGO」，此專輯在傳統廟會與喪禮伴奏裡找到新思維，將台灣傳統旋律五聲音階成功和宇宙概念融合，其音樂創作以傳統文化旋律為基底，並揭露了宇宙監獄太陽系的秘密，其內容最大的概念主要要讓各位知道「我們寫的事件不是虛構，我們只是把你所不知道的事實以虛構的方式呈現給你罷了」。同年底，血肉果汁機以「GIGO」此專輯拿下了第六屆金音獎最佳搖滾專輯獎 (6TH GOLDEN INDIE MUSIC AWARD-BEST ROCK ALBUM) 。且整張以「經書概念」打造的外殼包裝，也在2016年入圍金曲獎-專輯最佳設計獎。\n2017年，血肉發行「黑訊息」新EP、進行亞洲巡演，2018年推出新專輯「深海童話」、結合全息投影技術拍攝MV，並將展開一連串世界巡演。同年更榮獲金音創作獎最佳現場演出之肯定。2019年除入圍第三十屆金曲獎最佳樂團，更獲得了全美獨立音樂獎的專輯封面設計國際大獎。成軍至今 12 年，參與大大小小的國內外音樂祭巡迴表演，一步一腳印的把台灣的希望帶出去國外，讓世界聽到屬於台灣的在地故事。\n血肉果汁機在音樂上的風格，源自於台灣人的信仰文化，平時不會注意到的生活習慣，如今卻是備受矚目的關鍵來源。"
    },
    {
        "id": "bcband",
        "artist": "Beyond Cure（BC）",
        "band_img": "https://akstatic.streetvoice.com/profile_images/bc/ba/bcband/CXHnFY25VLizN2QB5q5836.jpeg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/bc/ba/bcband/dPQYQAaDTfno99cjJmrhGV.jpeg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 29,
        "follower": 333,
        "following": 28,
        "content": "性別：男\n\n全新陣容的BC將在音樂上建築更寬大場景，更意味將持續帶來更多突破與可能，新作品蛻變中的“藥物治療”也象徵BC即將重生的重要里程碑。這個過程沒有終點，而是不斷蛻變的開始。"
    },
    {
        "id": "OBSESS",
        "artist": "OBSESS",
        "band_img": "https://akstatic.streetvoice.com/profile_images/OB/SE/OBSESS/XmKH9qrPcGjCmtZdy4XbaB.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/OB/SE/OBSESS/KBTYuG4pVTpCVytcjR3CLQ.jpg",
        "type_": "音樂人",
        "place": "臺中市",
        "songs": 24,
        "follower": 2301,
        "following": 0,
        "content": "\n《OBSESS》\nOBSESS成立自2008年，樂團始終保持謹慎的態度，記錄每一件這個世界正在發生的故事，之後以極大化的情緒詮釋成曲。OBSESS的音樂早期受到Emo、Emo punk、Post hardcore的樂風影響極深,以如此直接並帶著豐富情感的音樂去衝擊聽眾的感官與思想，便是OBSESS一直在做的事。 \nOBSESS經常受邀參加台灣各大音樂節，共發行過三張作品：【INTERFERE(2010)】、【RISE IN ARMS(2013)】，【Tragic & Fantastic(2015)】。近年更相繼與歐美日本知名樂團【Story Of The Year】、【Bring Me The Horizon】、【Crossfaith】、【Adept】同台演出。\n試聽：indievox:http://www.indievox.com/obsessstreetvoice:http://tw.streetvoice.com/users/OBSESS/"
    },
    {
        "id": "crescentlament",
        "artist": "Crescent Lament / 恆月三途",
        "band_img": "https://akstatic.streetvoice.com/profile_images/cr/es/crescentlament/4710c9d862d011e5bf60441ea1600064.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/cr/es/crescentlament/65d20b0264094d7a9b908315e7a21e60.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 12,
        "follower": 192,
        "following": 5,
        "content": "\n成立於2007年的 Crescent Lament (中文團名：恆月三途)，以歌德金屬樂風與台灣本土文化作為創作基調，用音樂創造出深沈華麗的闇黑唯美氣氛，刻畫出台灣小人物的悲傷故事。Crescent Lament希望在音樂上表現出人心陰暗面的衝擊張力，除了憤怒的嘶吼、深沈的絕望、還摻雜著一絲絲可悲的期望。這也是Crescent Lament團名的意境：在充斥著各種負面情緒的寂靜暗夜中，新月一抹微弱的光芒，竟成人心可抓住的最後一絲希望。\nCrescent Lament第一張專輯【Behind the Lethal Deceit/末路之召】於2011年11月發行，內容以反戰為核心，與現今台灣面臨的衝突結合，利用音樂反思訴諸武力的愚闇與和諧共存的無價。在首張專輯發行後，Crescent Lament 決心讓創作更貼近台灣本土文化，在歷經三年半的籌劃與製作，於2015年6月推出第二張專輯【花殤/Elegy for the Blossoms】。【花殤】以台灣早年藝妲生活為藍本，描述日治時代到國民政府來台初期，台灣藝妲面對賣藝賣笑、送往迎來的人生，有著萬般不由己的感慨；全專輯以台語創作、並加入台日傳統民俗樂器，更道出台灣的歷史記憶跟時代的滄桑改變。\n• 重大演出經歷：-2008 野台開唱-2009 歐洲名團Lacrimosa世界巡迴 台北場開場樂團-2009 台灣名團 閃靈 世界巡迴 台北場開場樂團-2011 專輯【Behind the Lethal Deceit】首賣 全台巡迴-2012 韓國首爾金屬音樂祭“Extreme camp vol.2”受邀樂團-2012 巨獸搖滾音樂祭-2013 歐洲名團Epica世界巡迴 台北場開場樂團-2013 貢寮海洋音樂祭-2013 野台開唱-2013 巨獸搖滾音樂祭-2014 台南五月音樂祭-2014 巨獸搖滾音樂祭-2015 大港開唱-2015 專輯【花殤】首賣 全台巡迴\n• 音樂發行：-2008 EP【Crescent Lament】-2008 EP【The Forgotten Winter】-2011 專輯【Behind the Lethal Deceit/末路之召】-2015 專輯【花殤/Elegy for the Blossoms】"
    },
    {
        "id": "rainofsorrow",
        "artist": "煙雨飄渺 Rain of Sorrow",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ra/in/rainofsorrow/rqDxiM5F2bmTztJJpBhfen.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/ra/in/rainofsorrow/DrWLNSJSjYdnXAR4reucaE.png",
        "type_": "音樂人",
        "place": "高雄市",
        "songs": 16,
        "follower": 729,
        "following": 0,
        "content": "\n來自高雄。\n參加過覺醒音樂季、貢寮海洋音樂季、TAKAO ROCK Festival、春天吶喊音樂季、發條音樂節、烏魚季，以及全台大大小小Livehouse如台北Revolver、Pipe，台中迴響、嘉義傲頭厝、台南Tcrc、高雄LIVEWAREHOUSE、月光劇場、百樂門、水星酒館、屏東山羊飯館、宜蘭賣捌所...等演出。\n2016年於高雄百樂門舉辦首張EP《無法忘記的回憶》發片2017年於磚窯場舉辦《煙囪Chimney》單曲發片暨成軍兩年感謝祭。2019年於6月進行全台，北中南的《淪現Falls to Reality》專輯發片巡迴\n樂風以emo為基底，嘗試各種元素、變化節奏、吉他聲線、輕柔的細語呢喃與激昂的吶喊嘶吼，交織凝結成距離一萬公尺雨珠，墜落人最原始的情感，泛起巨大情緒漣漪，滲入平時用堅強偽裝的面具，拿下它，才發現早已淚流滿面。\n我們是 煙雨飄渺 Rain of Sorrow。"
    },
    {
        "id": "tobemusictw",
        "artist": "TOBE_TW Official",
        "band_img": "https://akstatic.streetvoice.com/profile_images/to/be/tobemusictw/VPFEwpJmnHRCHerz2pahZ2.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/to/be/tobemusictw/XUbrFNd5ghgpZQMnS2Sf9X.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 8,
        "follower": 77,
        "following": 0,
        "content": "\nTOBE_TW Official  Taiwanese Rock Band Since 2015\nTOBE樂團成立於2015年7月的台北，曲風以post-hardcore為基底，結合日系搖滾元素與新型態的拍點，試圖創造新的音樂風格，衝擊亞洲音樂圈。而樂團之所以稱為TOBE是因為to be的中文翻譯其實就是英文動詞(成為)的意思，就是希望所有聽到我們創作的人可以更深度的思考自己存在的意義，成為一個自己想成為的人 \"be the one who you want to be!\"，並在諧音的部份有著圖跟筆的意思，意味著我們將會在每個人的”圖”上，用我們的”筆”繪上讓人意想不到的篇章。\n购买请私讯粉专或来信，演出、配乐、歌曲制作等合作洽谈：tobemusictw@gmail.com\nFaceBook - https://www.facebook.com/tobemusicofficial/\nYouTube - http://www.youtube.com/c/TOBEchannel/\nSoundCloud - https://soundcloud.com/to-be-630950577\nTwitter - https://twitter.com/tobemusic_tw\nInstagram - https://www.instagram.com/tobemusicofficial/"
    },
    {
        "id": "y310",
        "artist": "YELLOW",
        "band_img": "https://akstatic.streetvoice.com/profile_images/y3/10/y310/2gErnvnaBDH6BAuWsoBvy6.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/y3/10/y310/G4yx4rcKFVikXCdfSxxzTY.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 11,
        "follower": 7110,
        "following": 3,
        "content": ""
    },
    {
        "id": "XUEIYUAN",
        "artist": "水源",
        "band_img": "https://akstatic.streetvoice.com/profile_images/XU/EI/XUEIYUAN/ShtdtcZdmDnJ9FFbnUqu4g.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/XU/EI/XUEIYUAN/WrMZMV2H9thpXgUtCt8KML.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 8,
        "follower": 1366,
        "following": 0,
        "content": "\n2018年2月，雷擎與余昊益正在進行一個四天寫完三首歌的高壓練習計畫，途中得知位於台北市水源路的舊有工作室即將四散的消息，這個忽如其來的打擊，因此解放了雷擎的能量，忽然能聽見朋友們嗓音中發亮的位置，音樂也跟著一句句流瀉而出。於是信心滿滿，拉住準備離開的朋友們，組成音樂組織—水源。\n水源招集眾多獨立樂團的創作者如馬克白、威愷爆炸、Boycany等，從台北到高雄、從地下到時尚，少年仔集結彼此力量，期待玩出獨樹一格且全面的作品。\n而水源所推出的同名之作，為即將解約的工作室所創作的告別歌曲為概念。處男EP內集結水源內部成員：余昊益、Wave、222Chopin，台語揉合英文，推出清涼B級勁曲〈風來吹〉、黏膩煽情〈Corny〉。它將會說明如何在10分鐘內完美詮釋你從沒聽過的新台語R&B。來自水源路臥房內的躁動新生力量，首度對外開放，為五月的台北，吹一陣CHILL咪咪的輕風。"
    },
    {
        "id": "dennischang",
        "artist": "Fish Stick 魚條樂團",
        "band_img": "https://akstatic.streetvoice.com/profile_images/de/nn/dennischang/kmsRgYYpP4jLjJaJZRdnym.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/de/nn/dennischang/NzZjYEp2DPk3XCgjtQUx6i.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 12,
        "follower": 1341,
        "following": 13,
        "content": ""
    },
    {
        "id": "MidisWonderland",
        "artist": "Midi 楊士弘",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Mi/di/MidisWonderland/ihirowstqknbwMg7tfUPfB.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Mi/di/MidisWonderland/aE3sHKuUfSNFBeVXCJKrb7.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 16,
        "follower": 533,
        "following": 23,
        "content": "性別：男\n\nFacebook粉專 www.facebook.com/MidisWonderland/Instagram專頁 www.instagram.com/midiswonderland/楊士弘 Midi Yang，帛琉出生，台南長大，臺北醫學大學畢業。 平常用木吉他詞曲創作，軟體與編曲苦手。\n於2018年五月發行人生第一張實體/數位EP『原來你是這種人』，其中『姓名』這首單曲獲得第九屆金音獎『最佳民謠單曲獎』入圍，現正籌備首張個人專輯中......\nYoutube頻道 www.youtube.com/channel/UC7oK9F2hm80-eRrnqntPuTg"
    },
    {
        "id": "RANDOM",
        "artist": "RANDOM",
        "band_img": "https://akstatic.streetvoice.com/profile_images/RA/ND/RANDOM/p1b0h24ddh13e119i91bc4thpql15.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/RA/ND/RANDOM/105ed8632c334a6fac679db1e4b475bb.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 16,
        "follower": 1462,
        "following": 68,
        "content": "性別：男\n\n Random隨性樂團成立於2005年底,融合了龐克、金屬、Funk等元素,以台語為主的創作路線在獨立音樂圈中風格鮮明。而主唱蛋糕充滿爆發力的怒吼、鼓手奔馳帶勁的敲擊、吉他手獨特的編曲與彈奏技巧,以及貝斯手在舞台上滿場飛的表演風格,每每煽動現場觀眾無法按奈的身體狂躁,不禁隨之群體騷動,看過的樂迷都對那強大熱情的現場氣氛留下深刻印象。 2012年發行了單曲《心內的歌》、《夢中世界》,並拿下貢寮國際海洋音樂祭最高榮譽 「海洋獨立大賞」,自此奠定Random隨性樂團在獨立樂團圈中的地位。2013年發行首張專輯《人生路途》,並受邀參加北京迷笛音樂節及日本SUMMER SONIC等國外大型音樂祭演出。 2015年全新專輯《良禽》,除了一貫以台語為主的創作,經過時光洗練而顯得更加成熟的創作思考與編曲風格,為歌曲注入了更多力量與情緒,展現強力回歸的企圖心。"
    },
    {
        "id": "KidKingTw",
        "artist": "孩子王（Kid King)",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Ki/dK/KidKingTw/29e1627e26f311e48e4ad8d385db02f2.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Ki/dK/KidKingTw/BxauUDFmTm2qkUR3nY3grk.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 4,
        "follower": 393,
        "following": 1,
        "content": "性別：男\n\n成立於2012年五月來自高雄，充滿詩意的台語搖滾樂團。淺白的台語歌詞藏著深厚詩意。細膩的吉他描繪著台灣意象；BASS與鼓緊密結合，每每直擊心臟。現場演出時，主唱的嘶吼聲勾出以為長大後就不會有的每個焦慮、痛苦、快樂、幸福。\n時間會帶走一切但帶不走你心中的 孩子王"
    },
    {
        "id": "staywideawake",
        "artist": "彼岸曙光Stay Wide Awake",
        "band_img": "https://akstatic.streetvoice.com/profile_images/st/ay/staywideawake/MxVXiopPrTRUMHRjGSrATD.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/st/ay/staywideawake/m9VAaSZZtRQ6GTtdMzLtAA.jpg",
        "type_": "音樂人",
        "place": "高雄市",
        "songs": 10,
        "follower": 268,
        "following": 1,
        "content": "性別：其他\n\n彼岸曙光成立於2011年的高雄，現任團員為Vocal-許淵智、Guitars-劉方毓、呂存恕、Bass-帥晨毅、Drums-周楷倫，曲風以Post Hardcore為基底，融合Modern Rock/Metal/Alternative等元素，而主唱許淵智童年時期深受西方靈魂樂及Deftones音樂氛圍影響，在創作表達方面亦不受傳統Post Hardcore流派框架所拘限。  　　近期作品為2017年底發行的數位EP【永遠地睡了Slept Forever】，描寫現代虛偽膚淺對原始真實靈魂的摧毀，黑暗淒美的旋律與碎裂人心的歌詞交織共舞，時而誘惑地呢喃吟唱，時而憤怒地炸裂嘶吼，讓內心那股絕望又焦躁不安的情緒赤裸地蔓延向這個世界。主唱獨特的唱腔與華麗深邃的編曲完美地相互穿透，帶有東方感的黑色底蘊為樂團的重要特色之一。"
    },
    {
        "id": "JADE_official_tw",
        "artist": "JADE",
        "band_img": "https://akstatic.streetvoice.com/profile_images/JA/DE/JADE_official_tw/te79BdbZM7kw88SVoDk2Mo.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/JA/DE/JADE_official_tw/TQvKow6XCiBcCvwudwajcU.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 8,
        "follower": 2065,
        "following": 1,
        "content": "性別：男\n\nIG: jade_official_twFB:JADE\n主唱/吉他 : 嘟嘟鼓 : AJ來自台北的 JADE 成軍於 2017 年年底， 是⼀支以 Guitar 和 Drum 為音樂主軸的 Alternative Rock 雙⼈樂團， 但 JADE 充滿⾃由性的音樂風格並不侷限於雙⼈組的現場演唱/奏， JADE 擅長以充滿節奏感的律動帶領聽眾進入他們倆營造的音樂氛圍。 Vocalist 嘟嘟擅長⽤粗糙卻又精緻的衝突感來彈奏吉他， 在音樂中表述⾃己對於世代的憤怒和⽣活的無奈， 時而又將⾃己的情感縮小回歸到感情之中。 玩團 10 多年的他內外能量在 JADE 組成後得到完全的爆發。 Drummer 阿傑利用與身俱來的肢體情緒付諸鼓音符生命， 超強的技巧在阿傑身上看起來就像是天⽣的， 讓他可以游刃有餘的將精⼒寄託在情緒之中， 充滿神經質的演奏讓 JADE 的音樂現場就像吃炸雞配可樂， 除了爽以外就是爽。"
    },
    {
        "id": "emptyorio",
        "artist": "Empty ORio",
        "band_img": "https://akstatic.streetvoice.com/profile_images/em/pt/emptyorio/R8vkXYShYrFHbosmKmjAHG.jpeg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/em/pt/emptyorio/CmNuh9XX9mjy4XnLGN8f5E.jpeg",
        "type_": "音樂人",
        "place": "",
        "songs": 11,
        "follower": 424,
        "following": 0,
        "content": ""
    },
    {
        "id": "Windmillband",
        "artist": "風籟坊 windmill",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Wi/nd/Windmillband/ZNqebccVWA7iCrmnpVuQZL.JPG?x-oss-process=image/resize,m_fill,h_600,w_600,limit_0/interlace,1/quality,q_95/sharpen,80/format,jpg), .jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Wi/nd/Windmillband/zCdXgfHYFrzTpL3q5TLpw8.JPG?x-oss-process=image/resize,m_fill,h_360,w_1920,limit_0/interlace,1/quality,q_95/sharpen,80/format,jpg), .jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 9,
        "follower": 1702,
        "following": 1,
        "content": "\n2007年春天成軍，發行了Demo甲（2008 ）、Demo乙（2009）；2011年完成了「Demo丙」的錄製，待續發表。\n自「2013 Baybeats Festival 」新加坡公開演出以來，不落足跡的「風籟坊」，隨即悄悄遁隱了起來。團員們各自遊走驛站間，穿梭於大小廳堂，漫步在山林田野，距離上一個場景，恍如隔世，若像昨日，沿路都是自言自語...\n鼓 陳泰元貝司 戴子吉他主唱 林已翔"
    },
    {
        "id": "keyfiguretw",
        "artist": "一點生",
        "band_img": "https://akstatic.streetvoice.com/profile_images/ke/yf/keyfiguretw/7c27fe2ef59011e391ed22000a8495a2.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/ke/yf/keyfiguretw/515ae6aafc81424abf0d7c946adb3ba9.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 3,
        "follower": 112,
        "following": 1,
        "content": "\n【一點生】直指萬事核心的人。一點生是來自四個不同樂團的樂手所組成。詞曲創作均以台語創作，在龐克的根基下擠壓出激烈的搖滾寸勁！"
    },
    {
        "id": "bugsofphonon",
        "artist": "聲子蟲",
        "band_img": "https://akstatic.streetvoice.com/profile_images/bu/gs/bugsofphonon/e66a247002b511e3a1d5123150003041.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_images/bu/gs/bugsofphonon/e66a247002b511e3a1d5123150003041.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 12,
        "follower": 910,
        "following": 63,
        "content": "性別：男\n\n蟲聲    微小而幽遠\n靜聽   溫柔卻強大\n一點一點     一即一切\n完全覆蓋"
    },
    {
        "id": "prairiewwww",
        "artist": "落差草原 WWWW",
        "band_img": "https://akstatic.streetvoice.com/profile_images/pr/ai/prairiewwww/WR6LfDUmkX4npPQS8Dt9EW.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/pr/ai/prairiewwww/CLDHSfL5h7nPdBsBofCVPb.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 39,
        "follower": 953,
        "following": 1,
        "content": "性別：其他\n\n落差草原 WWWW成立於2010年，台灣台北的實驗民謠樂團。音樂結合了詩歌、民謠、迷幻氛圍和部落感的音樂元素，喜歡以大自然作為創作靈感，並嘗試各種跨界演出。\nPrairie WWWW is an experimental folk band formed in Taipei, Taiwan in 2010. The music combines poetry, folk, ambient and tribal elements.The band seeks inspiration from the might of nature, and with a mixture of sounds and visual arts in their performances, they manage to bring forward to their audiences the experience of their unique soundscape visually and aurally."
    },
    {
        "id": "ZiXuanslowtrain",
        "artist": "黃子軒與山平快",
        "band_img": "https://akstatic.streetvoice.com/profile_images/Zi/Xu/ZiXuanslowtrain/sMk9qSy24KaFAXijduCYEL.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/Zi/Xu/ZiXuanslowtrain/2a615d8da8984c0d80701440273c69fb.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 16,
        "follower": 332,
        "following": 0,
        "content": "\n金曲獎最佳客語專輯得主。黃子軒以客家閩南血液為芯，敞開雙手接納多元文化的巨浪，在城市裡對於夢想的追求、對於生活的牢騷、對於家鄉的思念，都一一裝載在平快車中。\n「未來世代的客家歌謠」創造者，原「暗黑白領階級」2015年正式更名「黃子軒與山平快」。黃子軒以客家閩南血液為芯，敞開雙手接納多元文化的巨浪，在城市裡對於夢想的追求、對於生活的牢騷、對於家鄉的思念，都一一裝載在平快車中，用我們最熟悉的母語，唱出市井小民的心聲。\n創新的多元融合，不僅將客家音樂帶向前所未有的新境界，甚至被譽為『 未來世代的客家歌謠 』，黃子軒的音樂及現場實力同時也受到金曲獎、流行音樂原創音樂大獎、海洋音樂祭等國內俱公信力音樂指標獎項一致肯定，為樂壇中頗受各界看好的明日之星。"
    },
    {
        "id": "fiftybodyfifty",
        "artist": "五五身 FiftyBodyFifty",
        "band_img": "https://akstatic.streetvoice.com/profile_images/fi/ft/fiftybodyfifty/kUj3L4qCydbSpfRFPnxmoR.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/fi/ft/fiftybodyfifty/L2xDp7KgupDsxBNLnqYeZg.png",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 16,
        "follower": 2455,
        "following": 27,
        "content": "性別：男\n\n五五身的音樂以金盃鼓和木吉他為基底，野性蠢動的節奏中，電吉他優雅地飛翔、Bass吉他率性奔跑，譜出獨樹一格的曲風─既是激昂的民謠，也是詩意的搖滾樂。 \n2017年推出專輯《再一次雄性浪漫》後，演出現場總有人品味著歌詞，內心激動地流淚、總有人大聲地合唱，歡欣地和身旁樂迷互相衝撞。\n年輕的生命體驗了不平、期盼和失望後，這張作品《人類空虛簡史》探索人類文明和存在意義，在放任迷惘於知識中尋求啟發的同時，團員們各自拜訪崇拜的樂手前輩學習音樂的色彩、氣味和溫度，在四首歌裡演繹出旅程中更深沉、複雜的情緒。"
    },
    {
        "id": "liliumtaiwan",
        "artist": "百合花",
        "band_img": "https://akstatic.streetvoice.com/profile_images/li/li/liliumtaiwan/9aAZPp3WiYh6f67oZm9GmT.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/ch/ar/charlie82415/8d36f182ff064f27bd8ee5d5c99ec4c8.jpg",
        "type_": "音樂人",
        "place": "新北市",
        "songs": 54,
        "follower": 2152,
        "following": 14,
        "content": "生日 / 成立時間：2010 年 1 月 1 日\n\n台北人的河洛歌，讓我們赤腳在城市奔跑吧"
    },
    {
        "id": "twohours",
        "artist": "2HRs",
        "band_img": "https://akstatic.streetvoice.com/profile_images/tw/oh/twohours/41424202821611e4acd5d8d385db02f2.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/tw/oh/twohours/2HpKWDGTuYqFZUPNFaRG5b.jpg",
        "type_": "音樂人",
        "place": "",
        "songs": 22,
        "follower": 643,
        "following": 3,
        "content": "\n2HRs團名來自距離單位。分散在台南、台中、中壢，團員們聚首練團的平均車程就是兩小時，團名標示了這群理工人與眾不同的宇宙觀。來自台灣引以為傲的理工教育，團員大都從是科技相關工作，並熱愛著科幻小說。四人中有兩人受過正統的古典音樂訓練，紮實的樂理架構之外，帶電小提琴、合成器音色厚重，極富個人風格。2HRs顯然是台灣後搖滾的一記重拳。在2014年發行首張專輯「類星體」、2015年和台北電影節聯名發布專曲「德布希計畫」之後，2HRs在2015年底迎回了留學英國的合成器嗯哼，以及新鼓手一珍的到來，並朝著第二張專輯前進。\n演出、活動洽詢請請洽： 2HRsTaiwan@gmail.com\n"
    },
    {
        "id": "linion_linion",
        "artist": "LINION",
        "band_img": "https://akstatic.streetvoice.com/profile_images/li/ni/linion_linion/BVgrfpEpucTtRcPQ5b45Fo.png",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/li/ni/linion_linion/e4WdxzCUnwUuzhN3sLNoqd.jpg",
        "type_": "音樂人",
        "place": "新北市",
        "songs": 12,
        "follower": 4836,
        "following": 10,
        "content": "性別：男\n生日 / 成立時間：2 月 11 日\n\nLINION 藝人簡介以 Neo-Soul、R&B 為核心曲風的 LINION，是當今的台灣唱作人中，少數以貝斯為主奏樂器 的亮眼存在。2016 年自美國洛杉磯 MI 音樂學院畢業後，LINION 與台灣的獨立廠牌「奇清唱 片」在 SounCloud 平台結識，並於 2018 年合作推出首張專輯《Me In Dat Blue》，收穫關注 入圍第十屆金音創作獎「最佳節奏藍調專輯獎」。LINION 曾在洗腦單曲〈Room 335〉中融入唐詩，私密的情感紀錄浮現東方的靈性哲思。 2020 年與日本樂團 THREE1989 彼此賞識的合作曲〈Horoyoi Karasu〉，則共享起東京與台 北兩座城市的逍遙情。微醺時刻，人類打從心底不受拘束的玄妙律動，正是 LINION 的中低音 域伏流間最勾魂的秘密。Facebook Fan Page:https://www.facebook.com/linionlinion/Instagram:https://www.instagram.com/linion_linion/Soundcloud:https://soundcloud.com/linionlinion"
    },
    {
        "id": "RAiN_and_PiCTURE",
        "artist": "Rain and Picture",
        "band_img": "https://akstatic.streetvoice.com/profile_images/RA/iN/RAiN_and_PiCTURE/oaDh3QTFKP8qMFCQWTJ7En.jpg",
        "bg_img": "https://akstatic.streetvoice.com/profile_cover_images/RA/iN/RAiN_and_PiCTURE/QSeSZ24GKpy3Yo7tTCeJKi.jpg",
        "type_": "音樂人",
        "place": "臺北市",
        "songs": 4,
        "follower": 299,
        "following": 0,
        "content": "性別：女\n生日 / 成立時間：2013 年 1 月 1 日\n\n歲月的弧線持續蔓延陌生人彼此交錯經過有人沒有保留有些人心都傷透\n2014年開始的Rain and Picture\n洗煉過的青春快與慢的交會在豐富情緒中找到出路\nFacebook https://www.facebook.com/RnPoffical/Streetvoice http://tw.streetvoice.com/RAiN_and_PiCTURE/"
    }
]