export const eventData = [
    {
        "id": 1594,
        "event": "浮現祭2021",
        "event_url": "https://streetvoice.com/venue/activities/1594/",
        "time": "12:00",
        "city": "台中市",
        "venue": "中山路90號",
        "show_attendees": [
            "拍謝少年",
            "持修",
            "Night Keepers 守夜人",
            "老破麻 - Old Slut Distortion",
            "イルカポリス 海豚刑警",
            "老王樂隊",
            "甜約翰 Sweet John",
            "狗吠火車",
            "董事長樂團",
            "脫拉庫",
            "朱頭皮",
            "趙一豪",
            "康士坦的變化球",
            "逃走鮑伯",
            "EastWave",
            "BIKE機踏車樂團",
            "P!SCO",
            "dizLike",
            "月宵◇クレシェンテ",
            "Carnival",
            "無妄合作社No-nonsense Collective",
            "宋德鶴Iron Horn",
            "SADOG",
            "米老虎 MainLive",
            "許含光 Lumi",
            "荷爾蒙少年 Hormone Boys",
            "温蒂漫步 Wendy wander",
            "八三夭",
            "麋先生Mixer",
            "魏嘉瑩 Arrow Wei"
        ],
        "link_attendees": [
            "SorryYouth",
            "ChihSiou_",
            "nightkeepers2015",
            "OldSlutDistortion",
            "iruka527",
            "wearewang",
            "sweetjohnband",
            "gaopuihuechia",
            "chairman",
            "pigheadskin",
            "ConstantanChange",
            "bobistired",
            "EastWaveBand",
            "bike9662",
            "piscoband",
            "dizLike",
            "Cmypenis",
            "nononsensecollective",
            "ironhorn",
            "SADOG",
            "mainlive",
            "LumiXu",
            "lukechan168",
            "aun04178ofe",
            "831",
            "MixerMiSir",
            "arrowwei"
        ],
        "like": 391,
        "datetime": "2021 年 2 月 27 日",
        "weekday": "星期六",
        "event_fb": "https://emergelivehouse2.kktix.cc/events/gkr3tjs",
        "content": "【浮現祭2021】海線的浮現・海派的澎派​\n\nMonster Energy X Emerge Music Festival​\n\n　​\n\n日　期┃2021/2/27(六) － 2/28(日)​\n\n地　點┃山海一線－台中清水​\n\n地　址┃台中市清水區中山路90號​\n\n(自清水火車站可步行至舞台及各展區)​\n\n演出樂團┃拍謝少年．持修．守夜人．老破麻．老王樂隊．海豚刑警．甜約翰．狗吠火車．董事長樂團．脫拉庫．朱頭皮普拉斯未知之境 ft. 趙一豪．康士坦的變化球．逃走鮑伯．EastWave．BIKE機踏車樂團．P!SCO．dizLike．月宵◇クレシェンテ．Carnival．無妄合作社．宋德鶴．SADOG．米老虎．許含光．荷爾蒙少年．溫蒂漫步．八三夭．麋先生．魏嘉瑩 ➳ AND MORE　　​\n\n　​\n\n票　種┃　​\n\n10/19(一)中午12點 KKTIX準時開賣​\n\n售票連結 ➞ https://reurl.cc/14KRAm​\n\n❶ 早鳥雙日票 $1800​ #限量\n\n❷ 愛心雙日票 $900​\n\n⁂購買愛心票種請詳閱KKTIX身心障礙票券說明​\n\n⁂購票可使用電子藝fun券和振興券，振興券僅限KKTIX網站購票並以信用卡方式付款，請先向銀行登錄/綁定。\n\n　​\n\n❸『浮現祭2020保留票』觀眾可持原票卷入場。未取票者請『務必』於活動前至全家機台領取實體票卷並於入場時出示，票面上日期將印製2021活動時間。​\n\n　​\n\n☼　​\n\n　　​\n\n主辦單位┃浮現音樂 Emerge Music​\n\n冠名贊助┃Monster Energy​\n\n本活動獲文化部影視及流行音樂產業局補助​"
    },
    {
        "id": 1856,
        "event": "【2021諸羅祭Jurassic Festival】#領悟_起來",
        "event_url": "https://streetvoice.com/venue/activities/1856/",
        "time": "12:00",
        "city": "嘉義市",
        "venue": "嘉義文化創意產業園區",
        "show_attendees": [
            "吳青原",
            "王彙筑",
            "生炒鴨肉羹",
            "美秀集團",
            "The Tic Tac",
            "EastWave",
            "Crispy脆樂團",
            "青虫 aoi",
            "Who Cares 胡凱兒",
            "粗大Band"
        ],
        "link_attendees": [
            "yasakamark",
            "bbulter",
            "Eustache",
            "bisiugroup",
            "thetictac",
            "EastWaveBand",
            "skippylu",
            "AOIMUSHIBAND",
            "whocares2016",
            "thickbigband"
        ],
        "like": 104,
        "datetime": "2021 年 4 月 10 日",
        "weekday": "星期六",
        "event_fb": "https://jurassicfestival.kktix.cc/events/0410",
        "content": "【2021諸羅祭Jurassic Festival】#領悟_起來 音樂x市集x實境解謎xCOS\n\n\n領悟音樂 · 起來搖滾\n\n你各位聽團仔，準備好和愛團穿越回到諸羅城時代了嗎？Go！！！\n\n\n「諸羅」是嘉義的舊地名，是咱綻放青春的所在。\n\n為了改變校園演唱會的形式，以及提升嘉大的社團風氣，在2019年【諸羅祭Jurassic Festival】誕生了，並得到廣大的迴響與支持，所以2021年我們來了！\n\n我們全力打造一個大舞台，將嘉義出發的樂團，與在地的表演團隊，重新介紹給這片土地的鄉梓，也串聯了許多學生社團和來自各地的樂團，使形形色色的表演者可以嶄露頭角。\n\n\n你們知道...\n\n嘉義有三百年的歷史，可惜歷經了戰亂、地震、拆廟、盟軍轟炸等文化保存浩劫，變成一個沒有老街的古老小城，但卻有很多充滿故事的老屋座落在巷弄間，一個轉彎，處處都是驚喜。\n\n清朝時，諸羅城的四個城門各安祀著神明，就像村莊的東西南北營般的守護鄉梓，音樂就像要過護城河的橋樑，來到諸羅城，中營由城隍廟鎮守著，是人民的信仰中心，而我們期待【諸羅祭】成為桃城的音樂文化新信仰。\n\n\n🦖史忒龍要賴領大家進入諸羅城喽！ㄅㄨ~ㄅㄨ~\n\n#入口東門-襟山門\n\n諸羅建城三百年，尿尿小童基座為高山鐵路文化故事牆，描述嘉義市作為傳統木材城市，高山鐵路的起點。可愛的諸羅樹蛙演奏各種樂器，突顯嘉義管樂之都與諸羅樹蛙首次發現地點在嘉義。奔跑、哺育的梅花鹿則象徵台灣最早城柵諸羅城建城之始，荷蘭人記載梅花鹿奔馳於野的歷史。\n\n#藝能舞台北門-拱辰舞台\n\n1~2~3~到台灣，台灣有個阿里山，要到阿里山，北門驛站請上車，昔日阿里山森林鐵道的起點，現今是個拍照好景點。\n\n#第一舞台西門-帶海舞台\n\n嘉義文化路走九遍，腳底下踏的曾經你我的點點，我從日走到夜，食物從早點吃到宵夜，我多不想離開幸福指數第一的嘉義。\n\n#第二舞台南門-崇陽舞台\n\n火雞肉飯、煎粿、鴨肉麵、古早味早餐、東市場、筒仔米糕、牛雜湯、楊桃汁汽水、美乃滋涼麵、魯熟肉...零錢掏出來，褲頭解開來，通通給他吃起來。\n\n\n【2021諸羅祭Jurassic Festival】\n\n希望降低音樂祭的參與門檻，帶領大眾認識好音樂，更透過非制式的方介紹嘉義這塊土地，也打造藝能表演舞台，創造音樂祭更多不同的可能，還有還有絕對不能錯過我們市集和實境解謎還有COSPLAY，心動的話就馬上購票吧！\n\n這次我們領悟前人的經驗，再一次站起來，打造諸羅限定的音樂祭，讓學生站上大舞台，也讓觀眾認識這塊土地，更讓在地人能以此為榮耀。\n\n\n\n活 動 資 訊\n\n【2021諸羅祭Jurassic Festival】#領悟_起來\n\n日　　期｜2021/04/10(六) － 04/11(日)\n\n地　　點｜ 嘉義文化創意產業園區 (嘉義市西區中山路616號)\n\n演出陣容｜吳青原、王彙筑、生炒鴨肉羹 HJ Band、美秀集團、The Tic Tac、東波EastWave、Crispy脆樂團、青虫 aoi、胡凱兒、粗大Band … and more\n\n票　　價｜\n\n🔻嘉大醬油票 (嘉義大學學生限定) SOLD OUT\n\n🔻嘉大打醬油票 (嘉義大學學生限定)\n\n🔻校園大使票 NT$欲知詳情，請找校園大使\n\n🔻火雞票 NT$850\n\n🔻火雞肉票 NT$1050\n\n🔻火雞肉飯票 NT$1300\n\n🔻雙人套票 NT$2300\n\n🔻愛心票 (現場販售) NT$300\n\n🎯 售票連結：\n\nKKTIX｜https://jurassicfestival.kktix.cc/events/0410\n\n\n＊此次皆為電子票券，購票完成後即可取得，所有線上購票皆為雙日票。\n\n＊購票一律採實名制，請務必於購票時確實填寫，「每位參加者」的 < 真實姓名、手機、信箱、身分證號>(現場須出示有效證件核對)\n\n＊嘉大醬油票、嘉大打醬油票、校園大使票皆為發送優惠碼領票，遺失恕不補發。\n\n＊雙人套票需兩人同時兌換手環入場，遺失恕不補發。\n\n＊愛心票券說明：\n\n1.僅接受現場持證明辦理，張數有限，售完為止。\n\n2.持有〈身心障礙者權益保護法〉之身心障礙手冊者，可購買兩張愛心票 (持手冊者一張、陪同者一張)\n\n3.7-12歲兒童可購買愛心票，未滿12歲孩童須由至少一名已購票大人陪同入場\n\n4.6歲(含)以下兒童可免費入場，至少一名已購票大人陪同入場\n\n5.購買愛心票陪同者皆須同時驗證進場。\n\n\n∎ 優惠活動、演出陣容不漏看，追蹤粉絲專頁\n\nhttps://www.facebook.com/jurassicfestival\n\n∎ IG愛用者請追蹤 @jurassicfestival\n\nhttps://instagram.com/jurassicfestival\n\n∎ 搶先知道第一手消息，小龍專業寵粉，加入社群\n\n您已被邀請加入「諸羅祭活動資訊討論群」！請點選以下連結加入社群！\n\nhttps://reurl.cc/Ez9VGK\n\n\n主辦單位｜國立嘉義大學領悟音樂多媒體工作坊"
    },
    {
        "id": 1799,
        "event": "持修『以結婚為前提』- 高雄場",
        "event_url": "https://streetvoice.com/venue/activities/1799/",
        "time": "19:30",
        "city": "高雄市",
        "venue": "LIVE WAREHOUSE",
        "show_attendees": [
            "持修"
        ],
        "link_attendees": [
            "ChihSiou_"
        ],
        "like": 92,
        "datetime": "2021 年 2 月 21 日",
        "weekday": "星期日",
        "event_fb": "https://www.indievox.com/activity/detail/21_iV008003a",
        "content": "真男人，結婚嗎？\n\n結婚を前提に__________てください (⁎⁍̴̛ᴗ⁍̴̛⁎)\n\n\n持修社長大人的第一次\n\n專場《以結婚為前提》就獻給你們了\n\n\n2021/1/3 (日) 台北場 Legacy\n\n2021/1/24 (日)高雄場 LIVE WAREHOUSE\n\n\n2021你們需要的第一個酷東西，12/8 18:00 準時開賣！"
    },
    {
        "id": 1993,
        "event": "《 2021 大港開唱 𝐌𝐄𝐆𝐀𝐏𝐎𝐑𝐓 𝐅𝐞𝐬𝐭𝐢𝐯𝐚𝐥 》",
        "event_url": "https://streetvoice.com/venue/activities/1993/",
        "time": "12:00",
        "city": "高雄市",
        "venue": "駁二藝術特區",
        "show_attendees": [
            "唐鳳",
            "徐若瑄 Vivian Hsu",
            "Leo王",
            "美秀集團",
            "FUTURE AFTER A SECOND",
            "非人物種",
            "熱寫生 heat sketch",
            "逃走鮑伯",
            "倒車入庫 Reversing into Garage",
            "謎路人Way of Puzzle",
            "持修",
            "厭世少年",
            "The Fur.",
            "南西肯恩",
            "眠腦 Sleeping Brain",
            "緩緩 Huan Huan",
            "萬龍 WANLONG",
            "My Cat Eats My Hand",
            "Tizzy Bac",
            "吳柏蒼",
            "Wayne's so sad 傷心欲絕",
            "Green!Eyes",
            "Easy Shen",
            "胖虎 punkhoo",
            "阿飛西雅 APHASIA",
            "必順鄉村",
            "Flesh Juicer 血肉果汁機",
            "Beyond Cure（BC）",
            "Ru味春捲 Ru's Piano",
            "INFERNAL CHAOS",
            "OBSESS",
            "Crescent Lament / 恆月三途",
            "煙雨飄渺 Rain of Sorrow",
            "TOBE_TW Official",
            "Mind The Gap",
            "YELLOW",
            "鼓鼓 呂思緯",
            "康士坦的變化球",
            "イルカポリス 海豚刑警",
            "Asiaboy & Lizi 禁藥王 & 栗子Liz",
            "水源",
            "Fish Stick 魚條樂團",
            "Midi 楊士弘",
            "滅火器 Fire EX.",
            "RANDOM",
            "孩子王（Kid King)",
            "彼岸曙光Stay Wide Awake",
            "JADE",
            "Empty ORio",
            "風籟坊 windmill",
            "一點生",
            "陳珊妮",
            "拍謝少年",
            "聲子蟲",
            "落差草原 WWWW",
            "黃子軒與山平快",
            "五五身 FiftyBodyFifty",
            "百合花",
            "2HRs",
            "東京中央線",
            "LINION",
            "Rain and Picture"
        ],
        "link_attendees": [
            "leowangmorrison",
            "bisiugroup",
            "faasofficial",
            "punktv",
            "heatsketch",
            "bobistired",
            "RIGband",
            "wayofpuzzle",
            "ChihSiou_",
            "angry_youth",
            "thefurofficial",
            "nckn",
            "sleepingbrain",
            "huanhuantw",
            "wanlongband",
            "mycateatsmyhand",
            "tizzybac",
            "waynessosad",
            "greeneyesmusic",
            "punkhoo",
            "APHASIAtw",
            "fleshjuicer",
            "bcband",
            "OBSESS",
            "crescentlament",
            "rainofsorrow",
            "tobemusictw",
            "y310",
            "ConstantanChange",
            "iruka527",
            "XUEIYUAN",
            "dennischang",
            "MidisWonderland",
            "RANDOM",
            "KidKingTw",
            "staywideawake",
            "JADE_official_tw",
            "emptyorio",
            "Windmillband",
            "keyfiguretw",
            "SorryYouth",
            "bugsofphonon",
            "prairiewwww",
            "ZiXuanslowtrain",
            "fiftybodyfifty",
            "liliumtaiwan",
            "twohours",
            "linion_linion",
            "RAiN_and_PiCTURE"
        ],
        "like": 78,
        "datetime": "2021 年 3 月 27 日",
        "weekday": "星期六",
        "event_fb": "https://www.facebook.com/events/1999533290183911",
        "content": "2021年即將邁入第十二屆的《大港開唱》，是每年三月於高雄舉辦的大型音樂祭典，受到全台灣及日本、香港年輕觀眾的喜愛，近年已成為台灣最具指標性的大型戶外音樂祭活動。\n\n\n大港舉辦在高雄港邊，獨特的海港地景和人文風情，常勾起人生中各種酸甜苦辣的回憶。大港因此找來有著豐富人生歷程的知名藝人及業界前輩演出，或是與新一代的樂團或藝人一起合作，交融出世代之間的化學變化，往往成為當年度為人津津樂道的經典現場，包括《黃金夜總會》的賀一航、《古惑仔》裡的大飛哥-黃秋生，永駐在人們青春回憶中的日本偶像酒井法子，再到唱出《心事誰人知》的沈文程和演出《花甲男孩》的三金得主蔡振南。除此之外，唱著《少年吔，安啦！》的伍佰以及後來變成姐姐的謝金燕，也曾是大港舞台的主角之一。大明星們的風采在大港開唱魅力四射，震懾了台下的男男女女。\n\n\n當然，身為一個音樂祭，各種多元曲風和娛樂節目是絕對必備的。在大港「人生」與「音樂」的主題下，無論透過各種充滿個性的獨立音樂、生猛有力的搖滾或嘻哈，或是輕柔順耳的流行曲風，讓觀眾們生活中的喜怒哀樂、生命中的潮起潮落，在這個音樂的世界中得到了共鳴。歷年演出樂團的陣容集結了國內外實力堅強的藝人，包括茄子蛋、玖壹壹、草東沒有派對、9m88、Leo王、大象體操等等，每年近百組的演出藝人，搭配著意想不到的特別來賓做feat演出，每每都讓台下的樂迷驚喜連連，更是創造了南方港都風味的獨特回憶。\n\n\n同時，大港開唱也充份利用港都地理環境優勢，打造了近十個大小戶外室內舞台，包括在碼頭上打造的大型戶外舞台「南霸天」，還有在倉庫裡的「海龍王」、「卡魔麥」，在遊艇上的舞台「大雄丸」，在倉庫屋頂上的「出頭天」，歌廳秀舞台「藍寶石」，近年更增設「Kid𨑨迌」親子區、「Mega Fun」多功能遊樂區，當然也匯集了許多全台知名美食攤位、選物攤位以及NGO議題區等等。2021年更將首度啟用高雄流行音樂中心大型戶外廣場，設置大港史上最大戶外舞台「女神龍」。\n\n\n搖滾男女，別離相聚，親像海湧。十二年的大港開唱，就親像是港都的風情。十餘年下來，大港陪伴了許多觀眾從高中大學到結婚生子，和觀眾們一起走人生的路，帶給觀眾難忘的人生回憶，不只締造高雄著名全台的音樂場景，更成為耕耘十餘年有成的「人生的音樂祭」。\n\n\n人生不一定能夠看到所有的風景，也曾誤打誤撞被路途中的景色衝擊內心深處，因而留下深刻的印象，趕場的時候有時是一個人、有時是一群人，但真正的朋友總會有默契地在同一個地方遇見，只要一個眼神交會，我們就知道要一起往前衝、大聲吶喊，我們在散場時互相敲杯喝盡手中的啤酒，言語無需太多，此刻已進駐人生。\n\n\n人生的音樂祭，音樂祭的人生。\n\n \n\n\n活動日期：2021/03/27（六）-2021/03/28（日）\n\n活動地點：高雄駁二藝術特區 (地址：高雄市鹽埕區大勇路1號)\n\n主辦單位：出日音樂、高雄流行音樂中心\n\n協辦單位：高雄市政府文化局、高雄港務分公司\n\n指導單位：高雄市政府\n\n官網：https://lihi1.com/oikU5"
    },
    {
        "id": 1997,
        "event": "《更迭》康士坦的變化球－加場",
        "event_url": "https://streetvoice.com/venue/activities/1997/",
        "time": "20:00",
        "city": "台北市",
        "venue": "傳音樂展演空間",
        "show_attendees": [
            "康士坦的變化球"
        ],
        "link_attendees": [
            "ConstantanChange"
        ],
        "like": 37,
        "datetime": "2021 年 3 月 5 日",
        "weekday": "星期五",
        "event_fb": "https://www.indievox.com/activity/detail/21_iV0088286",
        "content": "演出日期及時間：2021/03/05 (五) 20:00\n\n演出地點：永豐Legacy Taipei 音樂展演空間\n\n演出者：康士坦的變化球\n\n票價：單人預售票1000元 / 雙人預售票1800元（一張900元，成套販售）（限量）/ 單人現場票1200元 / 身障票500元（僅限iNDIEVOX傳真訂購）\n\n售票時間：2021/01/18（一）12:00 開始販售\n\n\n迷惘的靈魂啊\n\n安靜地運轉吧\n\n忍耐的靈魂啊\n\n安靜地運轉吧\n\n\n在悲歡離合交織的世界擱淺\n\n只一首歌就可以超越"
    }
]